import {Platform, StyleSheet} from 'react-native';
import {fonts} from '../../../config/constants';
import type {AppColors} from '../../../config/theme/types';
import {hp, wp, responsiveSize} from '../../../utils/responsive';

export const createFeedDetailModalStyles = (colors: AppColors) =>
  StyleSheet.create({
    fullScreen: {
      flex: 1,
      backgroundColor: colors.modalSurface,
    },
    screenHeader: {
      position: 'relative',
      overflow: 'hidden',
      borderBottomWidth: 1,
      borderBottomColor: colors.primaryBorder,
    },
    screenHeaderGradient: {
      ...StyleSheet.absoluteFillObject,
    },
    screenHeaderContent: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: wp(4),
      paddingTop: hp(0.6),
      paddingBottom: hp(1.4),
      gap: wp(2.5),
    },
    backButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: wp(0.5),
      paddingRight: wp(1),
      flexShrink: 0,
    },
    backButtonLabel: {
      fontSize: responsiveSize(14),
      fontFamily: fonts.semibold,
      color: colors.primary,
    },
    screenHeaderMain: {
      flex: 1,
      minWidth: 0,
      flexDirection: 'row',
      alignItems: 'center',
      gap: wp(2.5),
    },
    headerIconWrap: {
      width: wp(10.5),
      height: wp(10.5),
      borderRadius: wp(2.8),
      backgroundColor: colors.primaryTint,
      borderWidth: 1,
      borderColor: colors.primaryBorder,
      alignItems: 'center',
      justifyContent: 'center',
      flexShrink: 0,
    },
    screenHeaderText: {
      flex: 1,
      minWidth: 0,
      gap: hp(0.2),
    },
    screenHeaderEyebrow: {
      fontSize: responsiveSize(9),
      fontFamily: fonts.bold,
      color: colors.primary,
      letterSpacing: responsiveSize(1.1),
    },
    screenHeaderTitle: {
      fontSize: responsiveSize(15),
      fontFamily: fonts.bold,
      color: colors.text,
      letterSpacing: responsiveSize(-0.2),
    },
    screenHeaderSubtitle: {
      fontSize: responsiveSize(11),
      fontFamily: fonts.regular,
      color: colors.textMuted,
    },
    headerSeverityPill: {
      flexShrink: 0,
      maxWidth: wp(24),
      paddingHorizontal: wp(2),
      paddingVertical: hp(0.45),
      alignItems: 'center',
    },
    headerSeverityText: {
      fontSize: responsiveSize(8),
      fontFamily: fonts.bold,
      letterSpacing: responsiveSize(0.5),
    },
    scrollView: {
      flex: 1,
    },
    scrollContent: {
      paddingHorizontal: wp(4),
      paddingTop: hp(1.5),
      paddingBottom: hp(4),
      width: '100%',
      flexGrow: 1,
    },
    playerCard: {
      position: 'relative',
      borderRadius: wp(4),
      marginBottom: hp(1.6),
      borderWidth: 1,
      borderColor: colors.primaryBorder,
      width: '100%',
    },
    playerCardContent: {
      width: '100%',
      paddingHorizontal: wp(3),
      paddingTop: hp(1.2),
      paddingBottom: hp(1.5),
      zIndex: 1,
    },
    playerHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: hp(0.9),
      width: '100%',
      gap: wp(2),
    },
    headerBadge: {
      flex: 1,
      minWidth: 0,
      maxWidth: wp(35),
      alignItems: 'center',
    },
    criticalBadge: {
      alignSelf: 'flex-start',
      backgroundColor: colors.primaryTint,
      borderRadius: wp(5),
      paddingHorizontal: wp(2.8),
      paddingVertical: hp(0.35),
      borderWidth: 1,
      borderColor: colors.primaryBorder,
    },
    criticalBadgeText: {
      fontSize: responsiveSize(9),
      fontFamily: fonts.bold,
      color: colors.primary,
      letterSpacing: responsiveSize(0.8),
    },
    warningBadge: {
      backgroundColor: 'rgba(245, 158, 11, 0.12)',
      borderColor: 'rgba(245, 158, 11, 0.4)',
    },
    warningBadgeText: {
      color: colors.warning,
    },
    infoBadge: {
      backgroundColor: 'rgba(107, 114, 128, 0.12)',
      borderColor: 'rgba(107, 114, 128, 0.35)',
    },
    infoBadgeText: {
      color: colors.textSecondary,
    },
    playerTimestamp: {
      flexShrink: 0,
      fontSize: responsiveSize(10.5),
      fontFamily: fonts.semibold,
      color: colors.textMuted,
      letterSpacing: 0.2,
      textAlign: 'right',
      maxWidth: '42%',
    },
    alertTitle: {
      fontSize: responsiveSize(20),
      fontFamily: fonts.bold,
      color: colors.text,
      marginBottom: hp(1.2),
      lineHeight: responsiveSize(26),
      letterSpacing: -0.2,
    },
    trackerRow: {
      width: '100%',
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: hp(0.5),
      marginBottom: hp(1.2),
      zIndex: 20,
      gap: wp(2),
    },
    trackerTimeLeft: {
      flex: 1,
      minWidth: 0,
      fontSize: responsiveSize(11),
      fontFamily: fonts.semibold,
      color: colors.textSecondary,
    },
    trackerRight: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'flex-end',
      flexShrink: 0,
      gap: wp(1.5),
      maxWidth: '52%',
    },
    trackerTimeRight: {
      fontSize: responsiveSize(11),
      fontFamily: fonts.semibold,
      color: colors.textSecondary,
      flexShrink: 1,
    },
    controlsRow: {
      width: '100%',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: wp(9),
      paddingTop: hp(0.2),
    },
    skipButton: {
      alignItems: 'center',
      justifyContent: 'center',
    },
    skipButtonRing: {
      width: wp(11),
      height: wp(11),
      borderRadius: wp(5.5),
      backgroundColor: colors.surfaceElevated,
      borderWidth: 1,
      borderColor: colors.border,
      alignItems: 'center',
      justifyContent: 'center',
    },
    skipIconWrap: {
      position: 'relative',
      alignItems: 'center',
      justifyContent: 'center',
    },
    skipLabel: {
      position: 'absolute',
      fontSize: responsiveSize(7.5),
      fontFamily: fonts.bold,
      color: colors.textSecondary,
    },
    playButtonOuter: {
      borderRadius: wp(8.5),
      padding: 3,
      backgroundColor: colors.primaryTint,
      ...Platform.select({
        ios: {
          shadowColor: colors.primary,
          shadowOffset: {width: 0, height: 4},
          shadowOpacity: 0.35,
          shadowRadius: 12,
        },
        android: {elevation: 8},
      }),
    },
    playButton: {
      width: wp(15),
      height: wp(15),
      borderRadius: wp(7.5),
      alignItems: 'center',
      justifyContent: 'center',
    },
    metaRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: wp(1.5),
      marginBottom: hp(1.6),
      width: '100%',
    },
    metaCard: {
      flexGrow: 1,
      flexBasis: '22%',
      minWidth: wp(18),
      maxWidth: '48%',
      position: 'relative',
      backgroundColor: colors.surfaceElevated,
      borderRadius: wp(3),
      borderWidth: 1,
      borderColor: colors.border,
      paddingVertical: hp(1.1),
      paddingHorizontal: wp(1.5),
      alignItems: 'center',
      overflow: 'hidden',
    },
    metaCardAccent: {
      position: 'absolute',
      top: 0,
      left: wp(2),
      right: wp(2),
      height: 2,
      backgroundColor: colors.primary,
      borderRadius: 1,
      opacity: 0.55,
    },
    metaLabel: {
      fontSize: responsiveSize(8),
      fontFamily: fonts.bold,
      color: colors.textMuted,
      letterSpacing: responsiveSize(0.8),
      marginBottom: hp(0.4),
      marginTop: hp(0.3),
    },
    metaValue: {
      fontSize: responsiveSize(12),
      fontFamily: fonts.bold,
      color: colors.metaValue,
      letterSpacing: responsiveSize(0.4),
      maxWidth: '100%',
    },
    feedContentCard: {
      backgroundColor: colors.surfaceElevated,
      borderRadius: wp(3.5),
      borderWidth: 1,
      borderColor: colors.border,
      paddingHorizontal: wp(3.5),
      paddingVertical: hp(1.5),
    },
    feedTalkgroupText: {
      fontSize: responsiveSize(11.5),
      fontFamily: fonts.semibold,
      color: colors.accent,
      marginBottom: hp(0.7),
      letterSpacing: 0.2,
    },
    notesSection: {
      marginTop: hp(1.2),
      backgroundColor: colors.surfaceElevated,
      borderRadius: wp(3.5),
      borderWidth: 1,
      borderColor: colors.border,
      paddingHorizontal: wp(3.5),
      paddingVertical: hp(1.5),
    },
    notesSectionTitle: {
      fontSize: responsiveSize(12),
      fontFamily: fonts.bold,
      color: colors.text,
      letterSpacing: responsiveSize(0.6),
      marginBottom: hp(0.4),
      textTransform: 'uppercase',
    },
    notesSectionHint: {
      fontSize: responsiveSize(11),
      fontFamily: fonts.regular,
      color: colors.textMuted,
      marginBottom: hp(1),
    },
    notesInput: {
      minHeight: hp(10),
      maxHeight: hp(16),
      backgroundColor: colors.inputBackground,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      borderRadius: wp(2.5),
      paddingHorizontal: wp(3),
      paddingVertical: hp(1.2),
      fontSize: responsiveSize(13),
      fontFamily: fonts.regular,
      color: colors.text,
      marginBottom: hp(1),
    },
    notesSaveButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: wp(1.5),
      backgroundColor: colors.primary,
      borderRadius: wp(2.5),
      paddingVertical: hp(1.1),
      marginBottom: hp(1.2),
    },
    notesSaveButtonDisabled: {
      opacity: 0.45,
    },
    notesSaveButtonText: {
      fontSize: responsiveSize(13),
      fontFamily: fonts.semibold,
      color: colors.textOnPrimary,
    },
    notesLoading: {
      marginVertical: hp(1),
    },
    notesEmptyText: {
      fontSize: responsiveSize(12),
      fontFamily: fonts.regular,
      color: colors.textMuted,
    },
    notesList: {
      gap: hp(0.8),
    },
    noteCard: {
      backgroundColor: colors.inputBackground,
      borderWidth: 1,
      borderColor: colors.menuItemBorder,
      borderRadius: wp(2.5),
      paddingHorizontal: wp(3),
      paddingVertical: hp(1),
    },
    noteCardHeader: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      marginBottom: hp(0.4),
      gap: wp(2),
    },
    noteMetaColumn: {
      flex: 1,
      minWidth: 0,
    },
    noteActions: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: wp(2.5),
    },
    noteDate: {
      fontSize: responsiveSize(10),
      fontFamily: fonts.semibold,
      color: colors.textMuted,
    },
    noteAuthor: {
      fontSize: responsiveSize(10),
      fontFamily: fonts.medium,
      color: colors.textSecondary,
      marginTop: hp(0.15),
    },
    notesEditInput: {
      minHeight: hp(8),
      backgroundColor: colors.inputBackground,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      borderRadius: wp(2.5),
      paddingHorizontal: wp(3),
      paddingVertical: hp(1),
      fontSize: responsiveSize(13),
      fontFamily: fonts.regular,
      color: colors.text,
      marginBottom: hp(0.8),
    },
    notesEditSaveButton: {
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primary,
      borderRadius: wp(2.5),
      paddingVertical: hp(0.9),
      marginBottom: hp(0.2),
    },
    noteBody: {
      fontSize: responsiveSize(13),
      fontFamily: fonts.regular,
      color: colors.text,
      lineHeight: responsiveSize(18),
    },
  });
