import {StyleSheet, Platform} from 'react-native';
import {fonts} from '../../../config/constants';
import type { AppColors } from "../../../config/theme/types";
import {
  COUNTY_FEED_CARD_WIDTH,
  hp,
  wp,
  responsiveSize,
} from '../../../utils/responsive';

export const TOOLBAR_BUTTON_SIZE = wp(10.5);

export const createStyles = (colors: AppColors) => StyleSheet.create({
  container: {
    flex: 1,
  },
  screenBody: {
    flex: 1,
  },
  toolbarRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: wp(4),
    marginBottom: hp(1.2),
    gap: wp(2.5),
  },
  searchBar: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: wp(2),
    backgroundColor: colors.inputBackground,
    borderRadius: wp(8),
    borderWidth: 1,
    borderColor: colors.menuItemBorder,
    paddingLeft: wp(4),
    paddingRight: wp(1.2),
    minHeight: TOOLBAR_BUTTON_SIZE,
    ...Platform.select({
      ios: {
        shadowColor: colors.shadow,
        shadowOffset: {width: 0, height: 2},
        shadowOpacity: 0.08,
        shadowRadius: 6,
      },
      android: {elevation: 2},
    }),
  },
  searchIcon: {
    flexShrink: 0,
  },
  searchInput: {
    flex: 1,
    minWidth: 0,
    fontSize: responsiveSize(14),
    fontFamily: fonts.regular,
    color: colors.text,
    paddingVertical: Platform.OS === 'ios' ? hp(1.2) : hp(0.9),
    paddingRight: 0,
  },
  searchBarFilterButton: {
    width: wp(9),
    height: wp(9),
    borderRadius: wp(2.2),
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    backgroundColor: colors.surfaceElevated,
    borderWidth: 1,
    borderColor: colors.menuItemBorder,
  },
  searchBarFilterButtonActive: {
    backgroundColor: colors.primaryTintStrong,
    borderColor: colors.primaryBorder,
  },
  filterIcon: {
    width: wp(5.3),
    height: wp(5.3),
    tintColor: colors.textMuted,
  },
  filterIconActive: {
    tintColor: colors.primary,
  },
  notificationButton: {
    width: TOOLBAR_BUTTON_SIZE,
    height: TOOLBAR_BUTTON_SIZE,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.primaryBorder,
    borderRadius: TOOLBAR_BUTTON_SIZE / 2,
    backgroundColor: colors.primaryTint,
    flexShrink: 0,
  },
  notificationIcon: {
    width: wp(5),
    height: wp(5),
    tintColor: colors.primary,
  },
  content: {
    paddingHorizontal: wp(4),
    paddingBottom: hp(5),
  },
  feedList: {
    flex: 1,
  },
  feedListContent: {
    paddingHorizontal: wp(3.5),
    paddingBottom: hp(2),
    flexGrow: 1,
  },
  feedSkeletonList: {
    gap: hp(0.55),
    paddingTop: hp(0.2),
  },
  feedSkeletonCard: {
    backgroundColor: colors.inputBackground,
    borderRadius: wp(3),
    paddingHorizontal: wp(2.8),
    paddingVertical: hp(1.1),
    borderWidth: 1,
    borderColor: colors.menuItemBorder,
  },
  feedSkeletonBlock: {
    borderRadius: wp(5),
    backgroundColor: colors.surfaceInset,
  },
  feedSkeletonCircle: {
    borderRadius: wp(5),
  },
  feedSkeletonHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: hp(1),
  },
  feedSkeletonHeaderCounty: {
    marginLeft: wp(1.2),
    flex: 1,
  },
  feedSkeletonHeaderActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: wp(1.2),
    marginLeft: wp(1.5),
  },
  feedSkeletonHeaderTime: {
    alignItems: 'flex-end',
    marginLeft: wp(1.5),
  },
  feedSkeletonTimeSecond: {
    marginTop: hp(0.25),
  },
  feedSkeletonLines: {
    gap: hp(0.55),
    marginBottom: hp(1),
  },
  feedSkeletonFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: wp(2),
  },
  feedSkeletonFooterLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: wp(1.2),
    flex: 1,
  },
  countySkeletonCard: {
    width: COUNTY_FEED_CARD_WIDTH,
    minHeight: hp(10.2),
    backgroundColor: colors.inputBackground,
    borderRadius: wp(3),
    paddingHorizontal: wp(2.8),
    paddingVertical: hp(1),
    marginRight: wp(2.2),
    borderWidth: 1,
    borderColor: colors.menuItemBorder,
    justifyContent: 'space-between',
  },
  countySkeletonBlock: {
    borderRadius: wp(2),
    backgroundColor: colors.surfaceInset,
  },
  countySkeletonShield: {
    borderRadius: wp(2),
    marginRight: wp(1.8),
  },
  countySkeletonHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: hp(0.55),
  },
  countySkeletonTitleBlock: {
    flex: 1,
    minWidth: 0,
    gap: hp(0.35),
    paddingRight: wp(1),
  },
  countySkeletonDot: {
    borderRadius: wp(999),
    marginTop: hp(0.35),
  },
  countySkeletonMetaRow: {
    marginBottom: hp(0.45),
  },
  countySkeletonFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: hp(0.2),
  },
  feedEmpty: {
    paddingVertical: hp(6),
    alignItems: 'center',
  },
  feedEmptyText: {
    fontSize: responsiveSize(14),
    fontFamily: fonts.regular,
    color: colors.textMuted,
    textAlign: 'center',
  },
  feedLoadMoreFooter: {
    paddingVertical: hp(1.8),
    alignItems: 'center',
    justifyContent: 'center',
    gap: hp(0.6),
  },
  feedLoadMoreText: {
    fontSize: responsiveSize(12),
    fontFamily: fonts.medium,
    color: colors.textMuted,
  },
  statusCard: {
    backgroundColor: colors.surface,
    borderRadius: wp(6),
    padding: wp(5),
    marginBottom: hp(3),
    borderWidth: 1,
    borderColor: colors.menuItemBorder,
  },
  statusTitle: {
    fontSize: responsiveSize(28),
    fontFamily: fonts.bold,
    color: colors.accent,
    marginBottom: hp(1.2),
  },
  statusSubtitle: {
    fontSize: responsiveSize(14),
    fontFamily: fonts.regular,
    color: colors.textSecondary,
    lineHeight: responsiveSize(20),
  },
  statusLive: {
    color: colors.live,
    fontFamily: fonts.semibold,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: hp(1),
  },
  sectionHeaderCompact: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: wp(4),
    marginBottom: hp(0.6),
  },
  sectionTitle: {
    fontSize: responsiveSize(24),
    fontFamily: fonts.bold,
    color: colors.text,
  },
  sectionTitleCompact: {
    fontSize: responsiveSize(15),
    fontFamily: fonts.bold,
    color: colors.text,
  },
  countBadge: {
    backgroundColor: colors.surfaceInset,
    borderRadius: wp(6),
    paddingVertical: hp(0.8),
    paddingHorizontal: wp(3),
  },
  countBadgeCompact: {
    backgroundColor: colors.surfaceInset,
    borderRadius: wp(4),
    paddingVertical: hp(0.35),
    paddingHorizontal: wp(2),
  },
  countBadgeText: {
    color: colors.textSecondary,
    fontSize: responsiveSize(12),
    fontFamily: fonts.semibold,
    letterSpacing: responsiveSize(0.5),
  },
  countBadgeTextCompact: {
    color: colors.textSecondary,
    fontSize: responsiveSize(9),
    fontFamily: fonts.semibold,
    letterSpacing: responsiveSize(0.4),
  },
  sectionCaption: {
    color: colors.accentMuted,
    fontSize: responsiveSize(11),
    fontFamily: fonts.medium,
    letterSpacing: responsiveSize(1.4),
    marginBottom: hp(2.4),
  },
  card: {
    backgroundColor: colors.inputBackground,
    borderRadius: wp(5),
    paddingVertical: hp(2.2),
    paddingHorizontal: wp(4),
    marginBottom: hp(2),
    borderWidth: 1,
    borderColor: colors.menuItemBorder,
  },
  cardRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  cardIconWrapper: {
    width: wp(12),
    height: wp(12),
    borderRadius: wp(4),
    backgroundColor: colors.surfaceInset,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: wp(4),
  },
  cardIconImage: {
    width: wp(5),
    height: wp(5),
  },
  cardText: {
    flex: 1,
  },
  cardTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: hp(0.5),
  },
  cardTitle: {
    fontSize: responsiveSize(18),
    fontFamily: fonts.bold,
    color: colors.text,
    marginBottom: hp(0.5),
  },
  cardMeta: {
    fontSize: responsiveSize(12),
    fontFamily: fonts.regular,
    color: colors.textSecondary,
    letterSpacing: responsiveSize(0.7),
    marginTop: hp(0.4),
  },
  cardEnd: {
    alignItems: 'flex-end',
  },
  dotWrapper: {
    width: wp(4.5),
    height: wp(4.5),
    borderRadius: wp(999),
    backgroundColor: `${colors.live}1A`,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: wp(2),
  },

  dot: {
    width: wp(2.2),
    height: wp(2.2),
    borderRadius: wp(999),
    backgroundColor: colors.live,

    shadowColor: colors.live,
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 1,
    shadowRadius: 10,
    elevation: 10,
  },
  chevron: {
    fontSize: responsiveSize(18),
    fontFamily: fonts.regular,
    color: colors.textSecondary,
    lineHeight: responsiveSize(18),
  },
  featureCard: {
    marginTop: hp(2.5),
    borderRadius: wp(6),
    padding: wp(5),
    marginBottom: hp(5),
    borderWidth: 1,
    borderColor: colors.menuItemBorder,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.1,
    shadowRadius: 18,
    elevation: 5,
  },
  featureTitle: {
    fontSize: responsiveSize(22),
    fontFamily: fonts.bold,
    color: colors.text,
    marginBottom: hp(1),
  },
  featureSubtitle: {
    fontSize: responsiveSize(12),
    fontFamily: fonts.medium,
    color: colors.live,
    letterSpacing: responsiveSize(1.2),
  },
  // Top Counties Horizontal Scroll Section Styles
  countiesHorizontalContainer: {
    marginBottom: hp(0.8),
    flexGrow: 0,
  },
  horizontalScrollContent: {
    paddingHorizontal: wp(4),
    paddingBottom: hp(0.4),
    alignItems: 'flex-start',
  },
  horizontalCard: {
    width: wp(38),
    height: hp(14),
    backgroundColor: colors.inputBackground,
    borderRadius: wp(4),
    padding: wp(3.5),
    marginRight: wp(3),
    borderWidth: 1,
    borderColor: colors.menuItemBorder,
    justifyContent: 'space-between',
    elevation: 4,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
  },
  horizontalCardCompact: {
    flexDirection: 'row',
    alignItems: 'center',
    width: wp(30),
    height: hp(5.2),
    backgroundColor: colors.inputBackground,
    borderRadius: wp(3),
    paddingHorizontal: wp(2.5),
    marginRight: wp(2),
    borderWidth: 1,
    borderColor: colors.menuItemBorder,
  },
  horizontalCardCompactSelected: {
    borderColor: colors.selectedTintBorder,
    backgroundColor: colors.selectedTintBg,
  },
  countyFeedCard: {
    width: COUNTY_FEED_CARD_WIDTH,
    minHeight: hp(10.2),
    backgroundColor: colors.inputBackground,
    borderRadius: wp(3),
    paddingHorizontal: wp(2.8),
    paddingVertical: hp(1),
    marginRight: wp(2.2),
    borderWidth: 1,
    borderColor: colors.menuItemBorder,
    justifyContent: 'space-between',
    elevation: 2,
    shadowColor: colors.shadow,
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.08,
    shadowRadius: 4,
  },
  countyFeedCardSelected: {
    borderColor: colors.selectedTintBorder,
    backgroundColor: colors.selectedTintBg,
  },
  countyFeedCardHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: hp(0.55),
  },
  countyFeedCardShield: {
    width: wp(7.2),
    height: wp(7.2),
    borderRadius: wp(2),
    borderWidth: 1.5,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: wp(1.8),
  },
  countyFeedCardShieldText: {
    fontSize: responsiveSize(10),
    fontFamily: fonts.bold,
    letterSpacing: responsiveSize(0.2),
  },
  countyFeedCardTitleBlock: {
    flex: 1,
    minWidth: 0,
    paddingRight: wp(1),
  },
  countyFeedCardTitle: {
    fontSize: responsiveSize(12.5),
    fontFamily: fonts.bold,
    color: colors.text,
  },
  countyFeedCardSubtitle: {
    marginTop: hp(0.1),
    fontSize: responsiveSize(9),
    fontFamily: fonts.regular,
    color: colors.textMuted,
  },
  countyFeedCardStatusDotWrap: {
    paddingTop: hp(0.35),
    paddingLeft: wp(0.5),
    flexShrink: 0,
  },
  countyFeedCardStatusDot: {
    width: wp(2.4),
    height: wp(2.4),
    borderRadius: wp(999),
    borderWidth: 1.5,
    borderColor: colors.surface,
  },
  countyFeedCardStatusDotOnline: {
    backgroundColor: colors.live,
  },
  countyFeedCardStatusDotOffline: {
    backgroundColor: colors.primary,
  },
  countyFeedCardStatusBadge: {
    borderRadius: wp(999),
    paddingHorizontal: wp(2),
    paddingVertical: hp(0.2),
    borderWidth: 1,
  },
  countyFeedCardStatusLive: {
    backgroundColor: colors.live + '22',
    borderColor: colors.live + '55',
  },
  countyFeedCardStatusActive: {
    backgroundColor: colors.warning + '22',
    borderColor: colors.warning + '55',
  },
  countyFeedCardStatusOffline: {
    backgroundColor: colors.surfaceInset,
    borderColor: colors.menuItemBorder,
  },
  countyFeedCardStatusText: {
    fontSize: responsiveSize(8),
    fontFamily: fonts.semibold,
    letterSpacing: responsiveSize(0.2),
  },
  countyFeedCardStatusTextLive: {
    color: colors.live,
  },
  countyFeedCardStatusTextActive: {
    color: colors.warning,
  },
  countyFeedCardStatusTextOffline: {
    color: colors.textMuted,
  },
  countyFeedCardLastActiveRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: wp(1.2),
    marginBottom: hp(0.45),
  },
  countyFeedCardLastActiveText: {
    fontSize: responsiveSize(9.5),
    fontFamily: fonts.regular,
    color: colors.textMuted,
    flex: 1,
  },
  countyFeedCardFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: wp(2),
    minWidth: 0,
  },
  countyFeedCardUsersRow: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: wp(1.2),
    minWidth: 0,
    flexShrink: 1,
  },
  countyFeedCardUsersText: {
    flex: 1,
    fontSize: responsiveSize(9.5),
    fontFamily: fonts.regular,
    color: colors.textMuted,
  },
  countyFeedCardViewLinkWrap: {
    flexShrink: 0,
    marginLeft: wp(1),
  },
  countyFeedCardViewLinkRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: wp(0.6),
  },
  countyFeedCardViewLink: {
    fontSize: responsiveSize(9.5),
    fontFamily: fonts.semibold,
    color: colors.primary,
  },
  horizontalCardIconWrapperCompact: {
    width: wp(7),
    height: wp(7),
    borderRadius: wp(2),
    backgroundColor: colors.surfaceInset,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: wp(2),
  },
  horizontalCardTextCompact: {
    flex: 1,
    minWidth: 0,
  },
  horizontalCardTitleCompact: {
    fontSize: responsiveSize(13),
    fontFamily: fonts.bold,
    color: colors.text,
  },
  horizontalCardMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: hp(0.15),
  },
  horizontalCardMetaCompact: {
    fontSize: responsiveSize(9),
    fontFamily: fonts.regular,
    color: colors.textMuted,
    letterSpacing: responsiveSize(0.2),
    flex: 1,
  },
  dotCompact: {
    width: wp(1.6),
    height: wp(1.6),
    borderRadius: wp(999),
    backgroundColor: colors.live,
    marginLeft: wp(1),
  },
  horizontalCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  horizontalCardIconWrapper: {
    width: wp(8.5),
    height: wp(8.5),
    borderRadius: wp(2.5),
    backgroundColor: colors.surfaceInset,
    justifyContent: 'center',
    alignItems: 'center',
  },
  horizontalCardIconImage: {
    width: wp(4),
    height: wp(4),
    tintColor: colors.accent,
  },
  horizontalCardContent: {
    marginTop: 'auto',
  },
  horizontalCardTitle: {
    fontSize: responsiveSize(16),
    fontFamily: fonts.bold,
    color: colors.text,
    marginBottom: hp(0.2),
  },
  horizontalCardMeta: {
    fontSize: responsiveSize(11),
    fontFamily: fonts.regular,
    color: colors.textSecondary,
    letterSpacing: responsiveSize(0.3),
  },
  chipsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  chip: {
    paddingVertical: hp(0.55),
    paddingHorizontal: wp(3.5),
    borderRadius: wp(999),
    backgroundColor: colors.surfaceInset,
    marginRight: wp(1.8),
    borderWidth: 1,
    borderColor: colors.menuItemBorder,
  },
  chipActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primaryBorder,
  },
  chipText: {
    fontSize: responsiveSize(11),
    fontFamily: fonts.bold,
    color: colors.textSecondary,
    letterSpacing: responsiveSize(0.5),
  },
  chipTextActive: {
    color: colors.textOnPrimary,
  },
  // Feed Item Card Styles
  feedItemCard: {
    backgroundColor: colors.inputBackground,
    borderRadius: wp(3),
    paddingHorizontal: wp(2.8),
    paddingVertical: hp(0.75),
    borderWidth: 1,
    borderColor: colors.menuItemBorder,
    elevation: 2,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
  },
  feedItemCardAlertBorder: {
    borderWidth: 1,
    overflow: 'hidden',
  },
  feedItemCardAlertPulse: {
    ...StyleSheet.absoluteFill,
    borderWidth: 1,
    borderRadius: wp(3),
  },
  feedItemHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: hp(0.35),
  },
  feedItemBadgeContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: wp(1.2),
    marginRight: wp(1),
    minWidth: 0,
  },
  feedBadge: {
    borderRadius: wp(2),
    paddingVertical: hp(0.15),
    paddingHorizontal: wp(1.6),
    marginRight: wp(1.2),
    flexShrink: 0,
  },
  feedBadgeText: {
    fontSize: responsiveSize(8),
    fontFamily: fonts.bold,
    letterSpacing: responsiveSize(0.4),
  },
  feedBadgeSeverityCritical: {
    backgroundColor: colors.primary,
  },
  feedBadgeSeverityWarning: {
    backgroundColor: colors.warning,
  },
  feedBadgeSeverityInfo: {
    backgroundColor: colors.live,
  },
  feedBadgeSeverityText: {
    color: colors.textOnPrimary,
  },
  feedCountyText: {
    flex: 1,
    minWidth: 0,
    fontSize: responsiveSize(10),
    color: colors.secure,
    fontFamily: fonts.bold,
    letterSpacing: responsiveSize(0.3),
  },
  feedTimeColumn: {
    alignItems: 'flex-end',
    flexShrink: 0,
    marginLeft: wp(0.5),
  },
  feedTimeText: {
    fontSize: responsiveSize(10),
    color: colors.textMuted,
    fontFamily: fonts.semibold,
  },
  feedTalkgroupRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: wp(1.5),
    marginBottom: hp(0.3),
  },
  feedTalkgroupPill: {
    alignSelf: 'flex-start',
    flexShrink: 1,
    maxWidth: '72%',
    backgroundColor: colors.surfaceInset,
    borderRadius: wp(2),
    paddingVertical: hp(0.3),
    paddingHorizontal: wp(2.2),
    borderWidth: 1,
    borderColor: colors.menuItemBorder,
  },
  feedTalkgroupText: {
    fontSize: responsiveSize(11),
    fontFamily: fonts.semibold,
    color: colors.accent,
  },
  feedSeverityPill: {
    borderRadius: wp(4),
    paddingHorizontal: wp(2.4),
    paddingVertical: hp(0.28),
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  feedSeverityPillText: {
    fontSize: responsiveSize(9),
    fontFamily: fonts.bold,
    color: colors.textOnPrimary,
    letterSpacing: responsiveSize(0.3),
  },
  feedSnippetText: {
    fontSize: responsiveSize(11),
    fontFamily: fonts.regular,
    color: colors.textSecondary,
    lineHeight: responsiveSize(14.5),
  },
  feedSnippetHighlight: {
    fontFamily: fonts.bold,
  },
  feedSnippetHighlightCritical: {
    color: colors.primary,
  },
  feedSnippetHighlightWarning: {
    color: colors.warning,
  },
  feedSnippetHighlightInfo: {
    color: colors.live,
  },

  feedStarButton: {
    padding: 0,
    width: wp(4.5),
    alignItems: 'center',
    flexShrink: 0,
  },
  feedStarIcon: {
    fontSize: responsiveSize(13),
    fontFamily: fonts.regular,
  },
  feedStarIconActive: {
    color: colors.starActive,
  },
  feedStarIconInactive: {
    color: colors.starInactive,
  },
  feedMetaText: {
    fontSize: responsiveSize(8.5),
    color: colors.textMuted,
    fontFamily: fonts.semibold,
    marginTop: hp(0.1),
  },
  feedCardWrapper: {
    marginBottom: hp(0.55),
  },
  feedCardWrapperExpanded: {
    marginBottom: hp(0.8),
  },
  feedCardActionButtonWrap: {
    position: 'relative',
  },
  feedCardActionButton: {
    width: wp(7),
    height: wp(7),
    borderRadius: wp(2),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surfaceInset,
    borderWidth: 1,
    borderColor: colors.menuItemBorder,
    marginRight: wp(1),
  },
  feedCardActionButtonActive: {
    backgroundColor: colors.primaryTint,
    borderColor: colors.primaryBorder,
  },
  feedCardNotesBadge: {
    position: 'absolute',
    top: -hp(0.35),
    right: -wp(0.8),
    minWidth: wp(3.6),
    height: wp(3.6),
    borderRadius: wp(999),
    paddingHorizontal: wp(0.6),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primary,
    borderWidth: 1,
    borderColor: colors.inputBackground,
  },
  feedCardNotesBadgeText: {
    fontSize: responsiveSize(8),
    fontFamily: fonts.bold,
    color: colors.textOnPrimary,
    lineHeight: responsiveSize(9),
  },
  feedCardHeaderActions: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: wp(0.5),
    flexShrink: 0,
  },
  feedCardBodyPressable: {
    width: '100%',
  },
  feedNotesPanel: {
    borderTopWidth: 1,
    borderTopColor: colors.menuItemBorder,
    marginTop: hp(0.6),
    paddingTop: hp(0.8),
    paddingHorizontal: wp(0.5),
    paddingBottom: hp(0.4),
    backgroundColor: colors.surfaceInset,
    borderBottomLeftRadius: wp(2.5),
    borderBottomRightRadius: wp(2.5),
  },
  feedNotesPanelHeader: {
    flexDirection: 'row',
    alignItems: 'baseline',
    justifyContent: 'space-between',
    marginBottom: hp(0.6),
    gap: wp(2),
  },
  feedNotesPanelTitle: {
    fontSize: responsiveSize(11),
    fontFamily: fonts.bold,
    color: colors.text,
    letterSpacing: responsiveSize(0.5),
    textTransform: 'uppercase',
  },
  feedNotesPanelHint: {
    fontSize: responsiveSize(9),
    fontFamily: fonts.regular,
    color: colors.textMuted,
    flex: 1,
    textAlign: 'right',
  },
  feedNotesInput: {
    minHeight: hp(7),
    maxHeight: hp(12),
    backgroundColor: colors.inputBackground,
    borderWidth: 1,
    borderColor: colors.inputBorder,
    borderRadius: wp(2),
    paddingHorizontal: wp(2.5),
    paddingVertical: hp(0.9),
    fontSize: responsiveSize(12),
    fontFamily: fonts.regular,
    color: colors.text,
    marginBottom: hp(0.6),
  },
  feedNotesSaveButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: wp(1.2),
    backgroundColor: colors.primary,
    borderRadius: wp(2),
    paddingVertical: hp(0.75),
    marginBottom: hp(0.7),
  },
  feedNotesSaveButtonDisabled: {
    opacity: 0.45,
  },
  feedNotesSaveButtonText: {
    fontSize: responsiveSize(11),
    fontFamily: fonts.semibold,
    color: colors.textOnPrimary,
  },
  feedNotesLoading: {
    marginVertical: hp(0.5),
  },
  feedNotesEmptyText: {
    fontSize: responsiveSize(11),
    fontFamily: fonts.regular,
    color: colors.textMuted,
    marginBottom: hp(0.3),
  },
  feedNotesList: {
    gap: hp(0.5),
  },
  feedNoteCard: {
    backgroundColor: colors.inputBackground,
    borderWidth: 1,
    borderColor: colors.menuItemBorder,
    borderRadius: wp(2),
    paddingHorizontal: wp(2.5),
    paddingVertical: hp(0.7),
  },
  feedNoteCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: hp(0.35),
    gap: wp(2),
  },
  feedNoteLabel: {
    fontSize: responsiveSize(11),
    fontFamily: fonts.semibold,
    color: colors.textSecondary,
  },
  feedNoteActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: wp(2),
  },
  feedNoteMeta: {
    fontSize: responsiveSize(9.5),
    fontFamily: fonts.regular,
    color: colors.textMuted,
    marginTop: hp(0.45),
  },
  feedNotesEditInput: {
    minHeight: hp(6),
    backgroundColor: colors.inputBackground,
    borderWidth: 1,
    borderColor: colors.inputBorder,
    borderRadius: wp(2),
    paddingHorizontal: wp(2.5),
    paddingVertical: hp(0.7),
    fontSize: responsiveSize(12),
    fontFamily: fonts.regular,
    color: colors.text,
    marginBottom: hp(0.5),
  },
  feedNotesEditSaveButton: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primary,
    borderRadius: wp(2),
    paddingVertical: hp(0.6),
    marginBottom: hp(0.2),
  },
  feedNoteBody: {
    fontSize: responsiveSize(12),
    fontFamily: fonts.regular,
    color: colors.text,
    lineHeight: responsiveSize(16),
    marginBottom: hp(0.1),
  },
  feedMetadataPanel: {
    borderTopWidth: 1,
    borderTopColor: colors.menuItemBorder,
    marginTop: hp(0.6),
    paddingTop: hp(1),
    paddingHorizontal: wp(1),
    paddingBottom: hp(0.6),
    backgroundColor: colors.surfaceElevated,
    borderBottomLeftRadius: wp(2.5),
    borderBottomRightRadius: wp(2.5),
  },
  feedMetadataPanelTitle: {
    fontSize: responsiveSize(11),
    fontFamily: fonts.bold,
    color: colors.accent,
    letterSpacing: responsiveSize(0.8),
    textTransform: 'uppercase',
    marginBottom: hp(0.8),
  },
  feedMetadataTable: {
    gap: hp(0.55),
  },
  feedMetadataRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: wp(3),
  },
  feedMetadataLabel: {
    flex: 1,
    fontSize: responsiveSize(12),
    fontFamily: fonts.regular,
    color: colors.textMuted,
  },
  feedMetadataValue: {
    flex: 1.2,
    fontSize: responsiveSize(12),
    fontFamily: fonts.semibold,
    color: colors.text,
    textAlign: 'right',
  },
  metadataSeverityBadge: {
    borderRadius: wp(4),
    paddingHorizontal: wp(2.5),
    paddingVertical: hp(0.25),
    minWidth: wp(16),
    alignItems: 'center',
  },
  metadataSeverityCritical: {
    backgroundColor: colors.primary,
  },
  metadataSeverityWarning: {
    backgroundColor: colors.warning,
  },
  metadataSeverityInfo: {
    backgroundColor: colors.live,
  },
  metadataSeverityBadgeText: {
    fontSize: responsiveSize(11),
    fontFamily: fonts.bold,
    color: colors.textOnPrimary,
  },
  feedMetadataDivider: {
    height: 1,
    backgroundColor: colors.menuItemBorder,
    marginVertical: hp(0.9),
  },
  feedMetadataKeywordsTitle: {
    fontSize: responsiveSize(12),
    fontFamily: fonts.bold,
    color: colors.text,
    marginBottom: hp(0.5),
  },
  feedMetadataKeywordsEmpty: {
    fontSize: responsiveSize(11),
    fontFamily: fonts.regular,
    color: colors.textMuted,
  },
  feedMetadataKeywordList: {
    gap: hp(0.5),
  },
  metadataKeywordPill: {
    alignSelf: 'flex-start',
    borderRadius: wp(4),
    paddingHorizontal: wp(3),
    paddingVertical: hp(0.55),
    maxWidth: '100%',
  },
  metadataKeywordPillCritical: {
    backgroundColor: colors.primary,
  },
  metadataKeywordPillWarning: {
    backgroundColor: colors.warning,
  },
  metadataKeywordPillInfo: {
    backgroundColor: colors.live,
  },
  metadataKeywordPillText: {
    fontSize: responsiveSize(12),
    fontFamily: fonts.semibold,
    color: colors.textOnPrimary,
  },
});
