import {StyleSheet, Platform} from 'react-native';
import {colors} from '../../../constants';
import {hp, wp, responsiveSize} from '../../../utils/responsive';
import {premium} from './styles';

export const editModalStyles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.72)',
    justifyContent: 'center',
    paddingHorizontal: wp(4),
    paddingVertical: hp(3),
  },
  card: {
    backgroundColor: premium.surface,
    borderRadius: wp(4),
    borderWidth: 1,
    borderColor: premium.borderStrong,
    maxHeight: '92%',
    overflow: 'hidden',
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: {width: 0, height: 12},
        shadowOpacity: 0.45,
        shadowRadius: 28,
      },
      android: {elevation: 14},
    }),
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: wp(5),
    paddingTop: hp(2.2),
    paddingBottom: hp(1.2),
  },
  headerTitle: {
    fontSize: responsiveSize(20),
    fontWeight: '700',
    color: colors.white,
  },
  closeButton: {
    width: wp(9),
    height: wp(9),
    borderRadius: wp(2.2),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
  },
  tabsRow: {
    flexDirection: 'row',
    paddingHorizontal: wp(5),
    borderBottomWidth: 1,
    borderBottomColor: premium.border,
  },
  tab: {
    marginRight: wp(6),
    paddingBottom: hp(1.2),
    borderBottomWidth: 2,
    borderBottomColor: 'transparent',
  },
  tabActive: {
    borderBottomColor: premium.accent,
  },
  tabText: {
    fontSize: responsiveSize(14),
    fontWeight: '500',
    color: premium.textMuted,
  },
  tabTextActive: {
    color: premium.accent,
    fontWeight: '700',
  },
  body: {
    paddingHorizontal: wp(5),
    paddingTop: hp(2),
    paddingBottom: hp(1),
    maxHeight: hp(52),
  },
  bodyCompact: {
    paddingHorizontal: wp(5),
    paddingTop: hp(2),
    paddingBottom: hp(1),
  },
  fieldLabel: {
    fontSize: responsiveSize(13),
    color: premium.textMuted,
    marginBottom: hp(0.8),
    fontWeight: '500',
  },
  required: {
    color: premium.accent,
  },
  textInput: {
    borderWidth: 1,
    borderColor: premium.borderStrong,
    borderRadius: wp(2.5),
    paddingHorizontal: wp(3.5),
    paddingVertical: Platform.OS === 'ios' ? hp(1.3) : hp(1),
    fontSize: responsiveSize(14),
    color: colors.white,
    marginBottom: hp(2),
    backgroundColor: premium.searchBg,
  },
  roleSelect: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: premium.borderStrong,
    borderRadius: wp(2.5),
    paddingHorizontal: wp(3.5),
    paddingVertical: hp(1.3),
    marginBottom: hp(1),
    backgroundColor: premium.searchBg,
  },
  roleSelectText: {
    fontSize: responsiveSize(14),
    color: colors.white,
    fontWeight: '500',
  },
  roleOptions: {
    borderWidth: 1,
    borderColor: premium.borderStrong,
    borderRadius: wp(2.5),
    marginBottom: hp(2),
    overflow: 'hidden',
    backgroundColor: premium.surfaceRaised,
  },
  roleOption: {
    paddingHorizontal: wp(3.5),
    paddingVertical: hp(1.2),
    borderBottomWidth: 1,
    borderBottomColor: premium.border,
  },
  roleOptionActive: {
    backgroundColor: premium.accentSoft,
  },
  roleOptionText: {
    fontSize: responsiveSize(14),
    color: premium.textMuted,
  },
  roleOptionTextActive: {
    color: premium.accent,
    fontWeight: '700',
  },
  sectionTitle: {
    fontSize: responsiveSize(15),
    fontWeight: '700',
    color: colors.white,
    marginBottom: hp(0.5),
  },
  sectionSubtitle: {
    fontSize: responsiveSize(13),
    color: premium.textMuted,
    marginBottom: hp(1.8),
    lineHeight: responsiveSize(18),
  },
  countyToolbar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: wp(2),
    marginBottom: hp(1.5),
  },
  countySearch: {
    flex: 1,
    borderWidth: 1,
    borderColor: premium.borderStrong,
    borderRadius: wp(2.5),
    paddingHorizontal: wp(3),
    paddingVertical: Platform.OS === 'ios' ? hp(1.1) : hp(0.9),
    fontSize: responsiveSize(13),
    color: colors.white,
    backgroundColor: premium.searchBg,
  },
  selectAllButton: {
    borderWidth: 1,
    borderColor: premium.borderStrong,
    borderRadius: wp(2.5),
    paddingHorizontal: wp(3),
    paddingVertical: hp(1.1),
    backgroundColor: premium.surfaceRaised,
  },
  selectAllText: {
    fontSize: responsiveSize(12),
    fontWeight: '600',
    color: colors.white,
  },
  countyGrid: {
    borderWidth: 1,
    borderColor: premium.borderStrong,
    borderRadius: wp(2.5),
    padding: wp(2.5),
    maxHeight: hp(28),
    backgroundColor: premium.searchBg,
  },
  countyGridInner: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: wp(2),
  },
  countyItem: {
    width: '48%',
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: premium.borderStrong,
    borderRadius: wp(2.5),
    paddingHorizontal: wp(2.5),
    paddingVertical: hp(1.2),
    backgroundColor: premium.surfaceRaised,
    gap: wp(2),
  },
  countyItemSelected: {
    borderColor: 'rgba(255, 77, 77, 0.5)',
    backgroundColor: premium.accentSoft,
  },
  checkbox: {
    width: wp(4.5),
    height: wp(4.5),
    borderRadius: wp(1),
    borderWidth: 1.5,
    borderColor: premium.textMuted,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxChecked: {
    backgroundColor: premium.accent,
    borderColor: premium.accent,
  },
  countyName: {
    fontSize: responsiveSize(13),
    color: colors.white,
    fontWeight: '500',
    flex: 1,
  },
  footer: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    gap: wp(2.5),
    paddingHorizontal: wp(5),
    paddingVertical: hp(2),
    borderTopWidth: 1,
    borderTopColor: premium.border,
    backgroundColor: premium.surfaceRaised,
  },
  cancelButton: {
    borderWidth: 1,
    borderColor: premium.borderStrong,
    borderRadius: wp(2.5),
    paddingHorizontal: wp(4.5),
    paddingVertical: hp(1.2),
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
  },
  cancelButtonText: {
    fontSize: responsiveSize(14),
    fontWeight: '600',
    color: premium.textMuted,
  },
  updateButton: {
    backgroundColor: premium.accent,
    borderRadius: wp(2.5),
    paddingHorizontal: wp(4.5),
    paddingVertical: hp(1.2),
    ...Platform.select({
      ios: {
        shadowColor: premium.accent,
        shadowOffset: {width: 0, height: 4},
        shadowOpacity: 0.35,
        shadowRadius: 8,
      },
      android: {elevation: 4},
    }),
  },
  updateButtonText: {
    fontSize: responsiveSize(14),
    fontWeight: '700',
    color: colors.white,
  },
});
