import {StyleSheet, Platform} from 'react-native';
import {fonts} from '../../../constants';
import type { AppColors } from "../../../theme/types";
import { hp, wp, responsiveSize } from '../../../utils/responsive';

export const TOOLBAR_BUTTON_SIZE = wp(10.5);

export const createStyles = (colors: AppColors) => StyleSheet.create({
  container: {
    flex: 1,
  },
  screenBody: {
    flex: 1,
  },
  toolbarRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: wp(4),
    marginBottom: hp(1.2),
    gap: wp(2.5),
  },
  searchBar: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: wp(2),
    backgroundColor: colors.inputBackground,
    borderRadius: wp(8),
    borderWidth: 1,
    borderColor: colors.menuItemBorder,
    paddingLeft: wp(4),
    paddingRight: wp(1.2),
    minHeight: TOOLBAR_BUTTON_SIZE,
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: {width: 0, height: 2},
        shadowOpacity: 0.2,
        shadowRadius: 6,
      },
      android: {elevation: 2},
    }),
  },
  searchIcon: {
    flexShrink: 0,
  },
  searchInput: {
    flex: 1,
    minWidth: 0,
    fontSize: responsiveSize(14),
    fontFamily: fonts.regular,
    color: colors.text,
    paddingVertical: Platform.OS === 'ios' ? hp(1.2) : hp(0.9),
    paddingRight: 0,
  },
  searchBarFilterButton: {
    width: wp(9),
    height: wp(9),
    borderRadius: wp(2.2),
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    backgroundColor: colors.surfaceElevated,
    borderWidth: 1,
    borderColor: colors.menuItemBorder,
  },
  searchBarFilterButtonActive: {
    backgroundColor: 'rgba(91, 64, 62, 0.9)',
    borderColor: 'rgba(255, 84, 81, 0.5)',
  },
  filterIcon: {
    width: wp(5.3),
    height: wp(5.3),
    tintColor: colors.textMuted,
  },
  filterIconActive: {
    tintColor: colors.primary,
  },
  notificationButton: {
    width: TOOLBAR_BUTTON_SIZE,
    height: TOOLBAR_BUTTON_SIZE,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 84, 81, 0.4)',
    borderRadius: TOOLBAR_BUTTON_SIZE / 2,
    backgroundColor: 'rgba(255, 84, 81, 0.12)',
    flexShrink: 0,
  },
  notificationIcon: {
    width: wp(5),
    height: wp(5),
    tintColor: colors.primary,
  },
  content: {
    paddingHorizontal: wp(4),
    paddingBottom: hp(5),
  },
  feedList: {
    flex: 1,
  },
  feedListContent: {
    paddingHorizontal: wp(3.5),
    paddingBottom: hp(2),
    flexGrow: 1,
  },
  statusCard: {
    backgroundColor: colors.surface,
    borderRadius: wp(6),
    padding: wp(5),
    marginBottom: hp(3),
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
  },
  statusTitle: {
    fontSize: responsiveSize(28),
    fontFamily: fonts.bold,
    color: '#A8B9E8',
    marginBottom: hp(1.2),
  },
  statusSubtitle: {
    fontSize: responsiveSize(14),
    fontFamily: fonts.regular,
    color: colors.textSecondary,
    lineHeight: responsiveSize(20),
  },
  statusLive: {
    color: '#4cd89f',
    fontFamily: fonts.semibold,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: hp(1),
  },
  sectionHeaderCompact: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: wp(4),
    marginBottom: hp(0.6),
  },
  sectionTitle: {
    fontSize: responsiveSize(24),
    fontFamily: fonts.bold,
    color: colors.text,
  },
  sectionTitleCompact: {
    fontSize: responsiveSize(15),
    fontFamily: fonts.bold,
    color: colors.text,
  },
  countBadge: {
    backgroundColor: '#111826',
    borderRadius: wp(6),
    paddingVertical: hp(0.8),
    paddingHorizontal: wp(3),
  },
  countBadgeCompact: {
    backgroundColor: '#111826',
    borderRadius: wp(4),
    paddingVertical: hp(0.35),
    paddingHorizontal: wp(2),
  },
  countBadgeText: {
    color: '#cbd5e1',
    fontSize: responsiveSize(12),
    fontFamily: fonts.semibold,
    letterSpacing: responsiveSize(0.5),
  },
  countBadgeTextCompact: {
    color: colors.textSecondary,
    fontSize: responsiveSize(9),
    fontFamily: fonts.semibold,
    letterSpacing: responsiveSize(0.4),
  },
  sectionCaption: {
    color: '#7b8aa6',
    fontSize: responsiveSize(11),
    fontFamily: fonts.medium,
    letterSpacing: responsiveSize(1.4),
    marginBottom: hp(2.4),
  },
  card: {
    backgroundColor: colors.inputBackground,
    borderRadius: wp(5),
    paddingVertical: hp(2.2),
    paddingHorizontal: wp(4),
    marginBottom: hp(2),
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.06)',
  },
  cardRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  cardIconWrapper: {
    width: wp(12),
    height: wp(12),
    borderRadius: wp(4),
    backgroundColor: '#1d2537',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: wp(4),
  },
  cardIconImage: {
    width: wp(5),
    height: wp(5),
  },
  cardText: {
    flex: 1,
  },
  cardTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: hp(0.5),
  },
  cardTitle: {
    fontSize: responsiveSize(18),
    fontFamily: fonts.bold,
    color: colors.text,
    marginBottom: hp(0.5),
  },
  cardMeta: {
    fontSize: responsiveSize(12),
    fontFamily: fonts.regular,
    color: colors.textSecondary,
    letterSpacing: responsiveSize(0.7),
    marginTop: hp(0.4),
  },
  cardEnd: {
    alignItems: 'flex-end',
  },
  dotWrapper: {
    width: wp(4.5),
    height: wp(4.5),
    borderRadius: wp(999),
    backgroundColor: 'rgba(49, 212, 146, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: wp(2),
  },

  dot: {
    width: wp(2.2),
    height: wp(2.2),
    borderRadius: wp(999),
    backgroundColor: '#4cd89f',

    shadowColor: '#4cd89f',
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 1,
    shadowRadius: 10,
    elevation: 10,
  },
  chevron: {
    fontSize: responsiveSize(18),
    fontFamily: fonts.regular,
    color: colors.textSecondary,
    lineHeight: responsiveSize(18),
  },
  featureCard: {
    marginTop: hp(2.5),
    borderRadius: wp(6),
    padding: wp(5),
    marginBottom: hp(5),
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.14,
    shadowRadius: 18,
    elevation: 5,
  },
  featureTitle: {
    fontSize: responsiveSize(22),
    fontFamily: fonts.bold,
    color: colors.text,
    marginBottom: hp(1),
  },
  featureSubtitle: {
    fontSize: responsiveSize(12),
    fontFamily: fonts.medium,
    color: '#4cd89f',
    letterSpacing: responsiveSize(1.2),
  },
  // Top Counties Horizontal Scroll Section Styles
  countiesHorizontalContainer: {
    marginBottom: hp(0.8),
    maxHeight: hp(6.5),
  },
  horizontalScrollContent: {
    paddingHorizontal: wp(4),
    paddingBottom: hp(0.4),
    alignItems: 'center',
  },
  horizontalCard: {
    width: wp(38),
    height: hp(14),
    backgroundColor: colors.inputBackground,
    borderRadius: wp(4),
    padding: wp(3.5),
    marginRight: wp(3),
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.06)',
    justifyContent: 'space-between',
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
  },
  horizontalCardCompact: {
    flexDirection: 'row',
    alignItems: 'center',
    width: wp(30),
    height: hp(5.2),
    backgroundColor: colors.inputBackground,
    borderRadius: wp(3),
    paddingHorizontal: wp(2.5),
    marginRight: wp(2),
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.06)',
  },
  horizontalCardCompactSelected: {
    borderColor: 'rgba(56, 189, 248, 0.65)',
    backgroundColor: 'rgba(47, 85, 151, 0.28)',
  },
  horizontalCardIconWrapperCompact: {
    width: wp(7),
    height: wp(7),
    borderRadius: wp(2),
    backgroundColor: '#1d2537',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: wp(2),
  },
  horizontalCardTextCompact: {
    flex: 1,
    minWidth: 0,
  },
  horizontalCardTitleCompact: {
    fontSize: responsiveSize(13),
    fontFamily: fonts.bold,
    color: colors.text,
  },
  horizontalCardMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: hp(0.15),
  },
  horizontalCardMetaCompact: {
    fontSize: responsiveSize(9),
    fontFamily: fonts.regular,
    color: '#64748b',
    letterSpacing: responsiveSize(0.2),
    flex: 1,
  },
  dotCompact: {
    width: wp(1.6),
    height: wp(1.6),
    borderRadius: wp(999),
    backgroundColor: '#4cd89f',
    marginLeft: wp(1),
  },
  horizontalCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  horizontalCardIconWrapper: {
    width: wp(8.5),
    height: wp(8.5),
    borderRadius: wp(2.5),
    backgroundColor: '#1d2537',
    justifyContent: 'center',
    alignItems: 'center',
  },
  horizontalCardIconImage: {
    width: wp(4),
    height: wp(4),
    tintColor: '#a8b9e8',
  },
  horizontalCardContent: {
    marginTop: 'auto',
  },
  horizontalCardTitle: {
    fontSize: responsiveSize(16),
    fontFamily: fonts.bold,
    color: colors.text,
    marginBottom: hp(0.2),
  },
  horizontalCardMeta: {
    fontSize: responsiveSize(11),
    fontFamily: fonts.regular,
    color: colors.textSecondary,
    letterSpacing: responsiveSize(0.3),
  },
  chipsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  chip: {
    paddingVertical: hp(0.55),
    paddingHorizontal: wp(3.5),
    borderRadius: wp(999),
    backgroundColor: '#111827',
    marginRight: wp(1.8),
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.06)',
  },
  chipActive: {
    backgroundColor: colors.primary,
    borderColor: 'rgba(47, 85, 151, 0.4)',
  },
  chipText: {
    fontSize: responsiveSize(11),
    fontFamily: fonts.bold,
    color: colors.textSecondary,
    letterSpacing: responsiveSize(0.5),
  },
  chipTextActive: {
    color: colors.text,
  },
  // Feed Item Card Styles
  feedItemCard: {
    backgroundColor: colors.inputBackground,
    borderRadius: wp(3),
    paddingHorizontal: wp(2.8),
    paddingVertical: hp(0.75),
    marginBottom: hp(0.55),
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.06)',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
  },
  feedItemCardAlertBorder: {
    borderWidth: 1,
  },
  feedItemHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: hp(0.35),
  },
  feedItemBadgeContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: wp(1.2),
    marginRight: wp(1.5),
  },
  feedBadge: {
    borderRadius: wp(2),
    paddingVertical: hp(0.15),
    paddingHorizontal: wp(1.6),
    marginRight: wp(1.4),
  },
  feedBadgeText: {
    fontSize: responsiveSize(8),
    fontFamily: fonts.bold,
    letterSpacing: responsiveSize(0.4),
  },
  feedBadgeFire: {
    backgroundColor: 'rgba(239, 68, 68, 0.15)',
  },
  feedBadgeFireText: {
    color: colors.primary,
  },
  feedBadgeMedical: {
    backgroundColor: 'rgba(59, 130, 246, 0.15)',
  },
  feedBadgeMedicalText: {
    color: colors.primary,
  },
  feedBadgePolice: {
    backgroundColor: 'rgba(245, 158, 11, 0.15)',
  },
  feedBadgePoliceText: {
    color: '#f59e0b',
  },
  feedBadgeGeneral: {
    backgroundColor: 'rgba(107, 114, 128, 0.15)',
  },
  feedBadgeGeneralText: {
    color: '#9ca3af',
  },
  feedCountyText: {
    flex: 1,
    fontSize: responsiveSize(10),
    color: '#38bdf8',
    fontFamily: fonts.bold,
    letterSpacing: responsiveSize(0.3),
  },
  feedTimeColumn: {
    alignItems: 'flex-end',
  },
  feedTimeText: {
    fontSize: responsiveSize(10),
    color: '#64748b',
    fontFamily: fonts.semibold,
  },
  feedTalkgroupRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: hp(0.25),
  },
  feedTalkgroupText: {
    flex: 1,
    fontSize: responsiveSize(11.5),
    fontFamily: fonts.semibold,
    color: '#a8b9e8',
    marginRight: wp(1.5),
  },
  feedSnippetText: {
    fontSize: responsiveSize(11),
    fontFamily: fonts.regular,
    color: '#cbd5e1',
    lineHeight: responsiveSize(14.5),
  },
  feedSnippetHighlight: {
    fontFamily: fonts.bold,
    color: colors.primary,
  },

  feedStarButton: {
    padding: 0,
    width: wp(4.5),
    alignItems: 'center',
  },
  feedStarIcon: {
    fontSize: responsiveSize(13),
    fontFamily: fonts.regular,
  },
  feedStarIconActive: {
    color: '#fbbf24',
  },
  feedStarIconInactive: {
    color: '#475569',
  },
  feedMetaText: {
    fontSize: responsiveSize(8.5),
    color: '#475569',
    fontFamily: fonts.semibold,
    marginTop: hp(0.1),
  },
});
