import {StyleSheet, Platform} from 'react-native';
import {fonts} from '../../../config/constants';
import type {AppColors} from '../../../config/theme/types';
import {hp, wp, responsiveSize} from '../../../utils/responsive';
import {createPremium} from './styles';

export const createEditModalStyles = (colors: AppColors) => {
  const premium = createPremium(colors);

  return StyleSheet.create({
    overlay: {
      flex: 1,
      backgroundColor: colors.overlay,
      justifyContent: 'center',
      paddingHorizontal: wp(4),
      paddingVertical: hp(3),
    },
    card: {
      backgroundColor: premium.surface,
      borderRadius: wp(4),
      borderWidth: 1,
      borderColor: premium.borderStrong,
      maxHeight: '92%',
      overflow: 'hidden',
      ...Platform.select({
        ios: {
          shadowColor: colors.shadow,
          shadowOffset: {width: 0, height: 12},
          shadowOpacity: 0.15,
          shadowRadius: 28,
        },
        android: {elevation: 14},
      }),
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: wp(5),
      paddingTop: hp(2.2),
      paddingBottom: hp(1.2),
    },
    headerTitle: {
      fontSize: responsiveSize(20),
      fontFamily: fonts.semibold,
      color: colors.text,
    },
    closeButton: {
      width: wp(9),
      height: wp(9),
      borderRadius: wp(2.2),
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.menuItemBorder,
    },
    tabsRow: {
      flexDirection: 'row',
      paddingHorizontal: wp(5),
      borderBottomWidth: 1,
      borderBottomColor: premium.border,
    },
    tab: {
      marginRight: wp(6),
      paddingBottom: hp(1.2),
      borderBottomWidth: 2,
      borderBottomColor: 'transparent',
    },
    tabActive: {
      borderBottomColor: premium.accent,
    },
    tabText: {
      fontSize: responsiveSize(14),
      fontFamily: fonts.medium,
      color: premium.textMuted,
    },
    tabTextActive: {
      color: premium.accent,
      fontFamily: fonts.semibold,
    },
    body: {
      paddingHorizontal: wp(5),
      paddingTop: hp(2),
      paddingBottom: hp(1),
      maxHeight: hp(52),
    },
    bodyCompact: {
      paddingHorizontal: wp(5),
      paddingTop: hp(2),
      paddingBottom: hp(1),
    },
    fieldLabel: {
      fontSize: responsiveSize(13),
      color: premium.textMuted,
      marginBottom: hp(0.8),
      fontFamily: fonts.medium,
    },
    required: {
      color: premium.accent,
    },
    textInput: {
      borderWidth: 1,
      borderColor: premium.borderStrong,
      borderRadius: wp(2.5),
      paddingHorizontal: wp(3.5),
      paddingVertical: Platform.OS === 'ios' ? hp(1.3) : hp(1),
      fontSize: responsiveSize(14),
      fontFamily: fonts.regular,
      color: colors.text,
      marginBottom: hp(2),
      backgroundColor: premium.searchBg,
    },
    roleSelect: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      borderWidth: 1,
      borderColor: premium.borderStrong,
      borderRadius: wp(2.5),
      paddingHorizontal: wp(3.5),
      paddingVertical: hp(1.3),
      marginBottom: hp(1),
      backgroundColor: premium.searchBg,
    },
    roleSelectText: {
      fontSize: responsiveSize(14),
      color: colors.text,
      fontFamily: fonts.medium,
    },
    roleOptions: {
      borderWidth: 1,
      borderColor: premium.borderStrong,
      borderRadius: wp(2.5),
      marginBottom: hp(2),
      overflow: 'hidden',
      backgroundColor: premium.surfaceRaised,
    },
    roleOption: {
      paddingHorizontal: wp(3.5),
      paddingVertical: hp(1.2),
      borderBottomWidth: 1,
      borderBottomColor: premium.border,
    },
    roleOptionActive: {
      backgroundColor: premium.accentSoft,
    },
    roleOptionText: {
      fontSize: responsiveSize(14),
      fontFamily: fonts.regular,
      color: premium.textMuted,
    },
    roleOptionTextActive: {
      color: premium.accent,
      fontFamily: fonts.semibold,
    },
    sectionTitle: {
      fontSize: responsiveSize(15),
      fontFamily: fonts.semibold,
      color: colors.text,
      marginBottom: hp(0.5),
    },
    sectionSubtitle: {
      fontSize: responsiveSize(13),
      fontFamily: fonts.regular,
      color: premium.textMuted,
      marginBottom: hp(1.8),
      lineHeight: responsiveSize(18),
    },
    countyToolbar: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: wp(2),
      marginBottom: hp(1.5),
    },
    countySearch: {
      flex: 1,
      borderWidth: 1,
      borderColor: premium.borderStrong,
      borderRadius: wp(2.5),
      paddingHorizontal: wp(3),
      paddingVertical: Platform.OS === 'ios' ? hp(1.1) : hp(0.9),
      fontSize: responsiveSize(13),
      fontFamily: fonts.regular,
      color: colors.text,
      backgroundColor: premium.searchBg,
    },
    selectAllButton: {
      borderWidth: 1,
      borderColor: premium.borderStrong,
      borderRadius: wp(2.5),
      paddingHorizontal: wp(3),
      paddingVertical: hp(1.1),
      backgroundColor: premium.surfaceRaised,
    },
    selectAllText: {
      fontSize: responsiveSize(12),
      fontFamily: fonts.semibold,
      color: colors.text,
    },
    countyGrid: {
      borderWidth: 1,
      borderColor: premium.borderStrong,
      borderRadius: wp(2.5),
      paddingVertical: hp(1.2),
      backgroundColor: premium.searchBg,
    },
    countyGridInner: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: wp(2),
      paddingHorizontal: wp(2.5),
    },
    countyItem: {
      flexDirection: 'row',
      alignItems: 'center',
      flexShrink: 0,
      maxWidth: wp(52),
      borderWidth: 1,
      borderColor: premium.borderStrong,
      borderRadius: wp(2.5),
      paddingHorizontal: wp(2.5),
      paddingVertical: hp(1.1),
      backgroundColor: premium.surfaceRaised,
      gap: wp(2),
    },
    countyItemSelected: {
      borderColor: 'rgba(255, 77, 77, 0.5)',
      backgroundColor: premium.accentSoft,
    },
    checkbox: {
      width: wp(4.5),
      height: wp(4.5),
      borderRadius: wp(1),
      borderWidth: 1.5,
      borderColor: premium.textMuted,
      alignItems: 'center',
      justifyContent: 'center',
    },
    checkboxChecked: {
      backgroundColor: premium.accent,
      borderColor: premium.accent,
    },
    countyName: {
      fontSize: responsiveSize(13),
      color: colors.text,
      fontFamily: fonts.medium,
      flex: 1,
      minWidth: 0,
    },
    countyLoadingText: {
      width: '100%',
      textAlign: 'center',
      fontSize: responsiveSize(13),
      fontFamily: fonts.medium,
      color: premium.textMuted,
      paddingVertical: hp(2),
    },
    footer: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
      alignItems: 'center',
      gap: wp(2.5),
      paddingHorizontal: wp(5),
      paddingVertical: hp(2),
      borderTopWidth: 1,
      borderTopColor: premium.border,
      backgroundColor: premium.surfaceRaised,
    },
    cancelButton: {
      borderWidth: 1,
      borderColor: premium.borderStrong,
      borderRadius: wp(2.5),
      paddingHorizontal: wp(4.5),
      paddingVertical: hp(1.2),
      backgroundColor: colors.menuItemBorder,
    },
    cancelButtonText: {
      fontSize: responsiveSize(14),
      fontFamily: fonts.semibold,
      color: premium.textMuted,
    },
    updateButton: {
      backgroundColor: premium.accent,
      borderRadius: wp(2.5),
      paddingHorizontal: wp(4.5),
      paddingVertical: hp(1.2),
      ...Platform.select({
        ios: {
          shadowColor: premium.accent,
          shadowOffset: {width: 0, height: 4},
          shadowOpacity: 0.35,
          shadowRadius: 8,
        },
        android: {elevation: 4},
      }),
    },
    updateButtonText: {
      fontSize: responsiveSize(14),
      fontFamily: fonts.semibold,
      color: colors.white,
    },
  });
};
