import {StyleSheet, Platform} from 'react-native';
import {fonts} from '../../../config/constants';
import {lightColors} from '../../../config/theme/colors';
import type {AppColors} from '../../../config/theme/types';
import {
  hp,
  wp,
  responsiveSize,
  TAB_BAR_HEIGHT,
} from '../../../utils/responsive';

export {TAB_BAR_HEIGHT};
export const ADD_BUTTON_SIZE = wp(10.5);

export const createPremium = (colors: AppColors) => {
  const isLight = colors.background === lightColors.background;

  return {
    bg: colors.background,
    surface: colors.surface,
    surfaceRaised: colors.surfaceElevated,
    searchBg: colors.inputBackground,
    accent: colors.primary,
    accentSoft: colors.primaryTint,
    border: colors.menuItemBorder,
    borderStrong: colors.borderMuted,
    textMuted: colors.textMuted,
    adminBadge: isLight ? '#FECACA' : '#6B2222',
    userBadge: isLight ? '#BBF7D0' : '#107C41',
    dispatcherBadge: isLight ? '#FDE68A' : '#5C4A1F',
    profileBg: colors.background,
    profileCard: colors.surface,
    profileCardSoft: isLight ? colors.surfaceInset : colors.surfaceElevated,
    profileBorder: isLight ? colors.border : colors.menuItemBorder,
    profileBorderStrong: colors.borderMuted,
    profileText: colors.text,
    profileTextMuted: colors.textMuted,
    profileTabActive: colors.primary,
    profileTabInactive: colors.textMuted,
    profilePrimaryButton: colors.primary,
    profilePrimaryButtonText: colors.textOnPrimary,
    profileDangerBorder: isLight
      ? 'rgba(232, 85, 82, 0.35)'
      : 'rgba(248, 113, 113, 0.45)',
    profileDangerBg: isLight
      ? 'rgba(232, 85, 82, 0.1)'
      : 'rgba(127, 29, 29, 0.25)',
    profileDangerText: isLight ? colors.primaryDark : '#FCA5A5',
    profileWarningBorder: isLight
      ? 'rgba(217, 119, 6, 0.35)'
      : 'rgba(251, 146, 60, 0.4)',
    profileWarningBg: isLight
      ? 'rgba(217, 119, 6, 0.08)'
      : 'rgba(69, 26, 3, 0.28)',
    profileWarningText: isLight ? colors.warning : '#FDBA74',
    profileInfoBg: isLight
      ? 'rgba(232, 85, 82, 0.06)'
      : colors.primaryTint,
    profileInfoBorder: colors.primaryBorder,
    profileInfoText: isLight ? colors.textSecondary : colors.text,
    profileRoleBg: isLight
      ? 'rgba(124, 58, 237, 0.12)'
      : 'rgba(76, 29, 149, 0.35)',
    profileRoleBorder: isLight
      ? 'rgba(124, 58, 237, 0.28)'
      : 'rgba(139, 92, 246, 0.5)',
    profileRoleText: isLight ? '#7C3AED' : '#C4B5FD',
    profileActiveBg: isLight
      ? 'rgba(5, 150, 105, 0.12)'
      : 'rgba(6, 78, 59, 0.45)',
    profileActiveBorder: isLight
      ? 'rgba(5, 150, 105, 0.28)'
      : 'rgba(16, 185, 129, 0.45)',
    profileActiveText: isLight ? colors.success : '#34D399',
    profileGhostText: isLight ? '#7C3AED' : '#C4B5FD',
    profileErrorText: isLight ? colors.primaryDark : '#F87171',
    roleBadgeTextAdmin: isLight ? '#991B1B' : colors.white,
    roleBadgeTextUser: isLight ? '#166534' : colors.white,
    roleBadgeTextDispatcher: isLight ? '#92400E' : colors.white,
  };
};

export const createStyles = (colors: AppColors) => {
  const premium = createPremium(colors);
  return StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: premium.bg,
  },
  list: {
    flex: 1,
  },
  listHeader: {
    paddingBottom: hp(1.2),
    gap: hp(1.4),
  },
  toolbarRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: wp(2.5),
  },
  searchBar: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: premium.surface,
    borderRadius: ADD_BUTTON_SIZE / 2,
    borderWidth: 1,
    borderColor: premium.borderStrong,
    paddingHorizontal: wp(4),
    minHeight: ADD_BUTTON_SIZE,
    ...Platform.select({
      ios: {
        shadowColor: colors.shadow,
        shadowOffset: {width: 0, height: 1},
        shadowOpacity: 0.06,
        shadowRadius: 4,
      },
      android: {elevation: 1},
    }),
  },
  searchIcon: {
    marginRight: wp(2.5),
  },
  searchInput: {
    flex: 1,
    minWidth: 0,
    fontSize: responsiveSize(14),
    fontFamily: fonts.regular,
    color: colors.text,
    paddingVertical: Platform.OS === 'ios' ? hp(1.2) : hp(0.9),
  },
  statsScroll: {
    marginHorizontal: -wp(4),
  },
  statsScrollContent: {
    paddingHorizontal: wp(4),
    gap: wp(2.5),
  },
  statCard: {
    width: wp(44),
    backgroundColor: premium.surface,
    borderRadius: wp(3.5),
    borderWidth: 1,
    borderColor: premium.border,
    paddingVertical: hp(1.3),
    paddingHorizontal: wp(3.2),
    ...Platform.select({
      ios: {
        shadowColor: colors.shadow,
        shadowOffset: {width: 0, height: 2},
        shadowOpacity: 0.06,
        shadowRadius: 5,
      },
      android: {elevation: 2},
    }),
  },
  statCardRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: wp(2.5),
  },
  statCardContent: {
    flex: 1,
    minWidth: 0,
    gap: hp(0.25),
  },
  statIconWrap: {
    width: wp(9),
    height: wp(9),
    borderRadius: wp(4.5),
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  statIconPurple: {
    backgroundColor: 'rgba(124, 58, 237, 0.12)',
  },
  statIconBlue: {
    backgroundColor: 'rgba(59, 130, 246, 0.12)',
  },
  statIconOrange: {
    backgroundColor: 'rgba(245, 158, 11, 0.12)',
  },
  statLabel: {
    fontSize: responsiveSize(11),
    fontFamily: fonts.medium,
    color: premium.textMuted,
  },
  statValue: {
    fontSize: responsiveSize(22),
    fontFamily: fonts.bold,
    color: colors.text,
    lineHeight: responsiveSize(26),
  },
  statSubLabel: {
    fontSize: responsiveSize(10),
    fontFamily: fonts.regular,
    color: premium.textMuted,
    lineHeight: responsiveSize(13),
  },
  roleChipsRow: {
    flexDirection: 'row',
    alignItems: 'stretch',
    gap: wp(2),
  },
  roleChip: {
    flex: 1,
    minWidth: 0,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: hp(1.05),
    paddingHorizontal: wp(2),
    borderRadius: wp(6),
    borderWidth: 1,
    borderColor: premium.borderStrong,
    backgroundColor: premium.surface,
  },
  roleChipActive: {
    backgroundColor: premium.accent,
    borderColor: premium.accent,
    ...Platform.select({
      ios: {
        shadowColor: premium.accent,
        shadowOffset: {width: 0, height: 2},
        shadowOpacity: 0.28,
        shadowRadius: 5,
      },
      android: {elevation: 3},
    }),
  },
  roleChipText: {
    fontSize: responsiveSize(12),
    fontFamily: fonts.semibold,
    color: colors.text,
    letterSpacing: responsiveSize(0.1),
    textAlign: 'center',
  },
  roleChipTextActive: {
    color: colors.textOnPrimary,
    fontFamily: fonts.semibold,
  },
  listContent: {
    paddingHorizontal: wp(4),
    gap: hp(1.2),
    flexGrow: 1,
  },
  listFooter: {
    width: '100%',
  },
  userSkeletonList: {
    gap: hp(1.2),
    paddingTop: hp(0.2),
  },
  userSkeletonCard: {
    backgroundColor: premium.surface,
    borderRadius: wp(3.5),
    borderWidth: 1,
    borderColor: premium.border,
    paddingHorizontal: wp(3.5),
    paddingVertical: hp(1.35),
    gap: hp(0.75),
    ...Platform.select({
      ios: {
        shadowColor: colors.shadow,
        shadowOffset: {width: 0, height: 2},
        shadowOpacity: 0.07,
        shadowRadius: 8,
      },
      android: {elevation: 2},
    }),
  },
  userSkeletonBlock: {
    borderRadius: wp(5),
    backgroundColor: colors.surfaceInset,
  },
  userSkeletonCircle: {
    borderRadius: wp(5),
  },
  userSkeletonHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: wp(2),
  },
  userSkeletonActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: wp(1.2),
    flexShrink: 0,
  },
  userSkeletonLines: {
    gap: hp(0.45),
  },
  userSkeletonFooter: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: wp(3),
  },
  userSkeletonFooterLeft: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: wp(1.2),
    minWidth: 0,
  },
  userSkeletonFooterRight: {
    alignItems: 'flex-end',
    gap: hp(0.25),
    minWidth: wp(22),
  },
  userCard: {
    flexDirection: 'row',
    backgroundColor: premium.surface,
    borderRadius: wp(3.5),
    borderWidth: 1,
    borderColor: premium.border,
    overflow: 'hidden',
    ...Platform.select({
      ios: {
        shadowColor: colors.shadow,
        shadowOffset: {width: 0, height: 2},
        shadowOpacity: 0.07,
        shadowRadius: 8,
      },
      android: {elevation: 2},
    }),
  },
  userCardBody: {
    flex: 1,
    minWidth: 0,
    paddingVertical: hp(1.35),
    paddingHorizontal: wp(3.5),
    gap: hp(0.75),
  },
  cardHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: wp(2),
  },
  cardTitleBlock: {
    flex: 1,
    minWidth: 0,
    gap: hp(0.35),
  },
  emailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: wp(1.5),
    minWidth: 0,
  },
  cardActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: wp(1.2),
    flexShrink: 0,
  },
  actionButton: {
    width: wp(8.8),
    height: wp(8.8),
    borderRadius: wp(2.6),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(59, 130, 246, 0.12)',
    borderWidth: 1,
    borderColor: 'rgba(59, 130, 246, 0.2)',
  },
  actionButtonDanger: {
    backgroundColor: 'rgba(239, 68, 68, 0.1)',
    borderColor: 'rgba(239, 68, 68, 0.22)',
  },
  actionButtonDisabled: {
    opacity: 0.35,
  },
  emailText: {
    fontSize: responsiveSize(15),
    fontFamily: fonts.bold,
    color: colors.text,
    letterSpacing: responsiveSize(0.05),
  },
  youBadge: {
    backgroundColor: premium.accentSoft,
    borderRadius: wp(1.5),
    borderWidth: 1,
    borderColor: 'rgba(255, 77, 77, 0.35)',
    paddingHorizontal: wp(1.8),
    paddingVertical: hp(0.25),
    flexShrink: 0,
  },
  youBadgeText: {
    fontSize: responsiveSize(9),
    fontFamily: fonts.bold,
    color: premium.accent,
    letterSpacing: responsiveSize(0.8),
  },
  roleBadge: {
    alignSelf: 'flex-start',
    borderRadius: wp(1.5),
    paddingHorizontal: wp(2.2),
    paddingVertical: hp(0.28),
  },
  roleBadgeAdmin: {
    backgroundColor: premium.adminBadge,
  },
  roleBadgeUser: {
    backgroundColor: premium.userBadge,
  },
  roleBadgeDispatcher: {
    backgroundColor: premium.dispatcherBadge,
  },
  roleBadgeText: {
    fontSize: responsiveSize(10),
    fontFamily: fonts.bold,
    letterSpacing: responsiveSize(0.5),
    color: colors.white,
  },
  roleBadgeTextAdmin: {
    color: premium.roleBadgeTextAdmin,
  },
  roleBadgeTextUser: {
    color: premium.roleBadgeTextUser,
  },
  roleBadgeTextDispatcher: {
    color: premium.roleBadgeTextDispatcher,
  },
  cardMetaRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: wp(3),
  },
  metaColumn: {
    flex: 1,
    minWidth: 0,
    gap: hp(0.2),
  },
  metaColumnEnd: {
    flex: 0,
    minWidth: wp(22),
    alignItems: 'flex-end',
  },
  metaLabel: {
    fontSize: responsiveSize(10),
    fontFamily: fonts.medium,
    color: premium.textMuted,
    letterSpacing: responsiveSize(0.2),
  },
  metaValue: {
    fontSize: responsiveSize(12),
    fontFamily: fonts.semibold,
    color: colors.text,
  },
  presenceBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    gap: wp(1),
    maxWidth: '100%',
    paddingHorizontal: wp(2.2),
    paddingVertical: hp(0.35),
    borderRadius: wp(5),
    borderWidth: 1,
  },
  presenceBadgeOnline: {
    backgroundColor: 'rgba(76, 216, 159, 0.1)',
    borderColor: 'rgba(76, 216, 159, 0.28)',
  },
  presenceBadgeAway: {
    backgroundColor: 'rgba(245, 158, 11, 0.1)',
    borderColor: 'rgba(245, 158, 11, 0.28)',
  },
  presenceBadgeOffline: {
    backgroundColor: premium.surfaceRaised,
    borderColor: premium.borderStrong,
  },
  presenceDot: {
    width: wp(1.7),
    height: wp(1.7),
    borderRadius: wp(0.85),
  },
  presenceDotOnline: {
    backgroundColor: colors.live,
  },
  presenceDotAway: {
    backgroundColor: colors.warning,
  },
  presenceDotOffline: {
    backgroundColor: premium.textMuted,
  },
  presenceBadgeText: {
    fontSize: responsiveSize(10),
    fontFamily: fonts.bold,
    letterSpacing: responsiveSize(0.5),
  },
  presenceTextOnline: {
    color: colors.live,
  },
  presenceTextAway: {
    color: colors.warning,
  },
  presenceTextOffline: {
    color: premium.textMuted,
  },
  presenceLastSeen: {
    flexShrink: 1,
    fontSize: responsiveSize(10),
    fontFamily: fonts.medium,
    color: premium.textMuted,
  },
  createdText: {
    fontSize: responsiveSize(11),
    color: premium.textMuted,
    fontFamily: fonts.regular,
    marginTop: hp(0.1),
  },
  addButtonWrap: {
    width: ADD_BUTTON_SIZE,
    height: ADD_BUTTON_SIZE,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  emptyState: {
    paddingVertical: hp(8),
    alignItems: 'center',
  },
  emptyStateText: {
    fontSize: responsiveSize(14),
    fontFamily: fonts.regular,
    color: premium.textMuted,
  },
  addButtonRing: {
    ...StyleSheet.absoluteFill,
    borderRadius: ADD_BUTTON_SIZE / 2,
    backgroundColor: 'rgba(255, 77, 77, 0.12)',
  },
  addButton: {
    width: ADD_BUTTON_SIZE,
    height: ADD_BUTTON_SIZE,
    borderRadius: ADD_BUTTON_SIZE / 2,
    backgroundColor: premium.accent,
    alignItems: 'center',
    justifyContent: 'center',
    ...Platform.select({
      ios: {
        shadowColor: premium.accent,
        shadowOffset: {width: 0, height: 4},
        shadowOpacity: 0.45,
        shadowRadius: 8,
      },
      android: {elevation: 6},
    }),
  },
  notificationButton: {
    width: ADD_BUTTON_SIZE,
    height: ADD_BUTTON_SIZE,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.primaryBorder,
    borderRadius: ADD_BUTTON_SIZE / 2,
    backgroundColor: colors.primaryTint,
    flexShrink: 0,
  },
  notificationIcon: {
    width: wp(5),
    height: wp(5),
    tintColor: colors.primary,
  },
  profileOverlay: {
    flex: 1,
    backgroundColor: premium.profileBg,
  },
  profileSheet: {
    flex: 1,
    backgroundColor: premium.profileBg,
    paddingHorizontal: wp(4),
    paddingTop: hp(1.8),
    paddingBottom: hp(1),
  },
  profileHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: wp(2.5),
  },
  profileHeaderMain: {
    flexDirection: 'row',
    gap: wp(2.8),
    flex: 1,
    minWidth: 0,
  },
  profileAvatar: {
    width: wp(12),
    height: wp(12),
    borderRadius: wp(3.4),
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileAvatarText: {
    fontFamily: fonts.bold,
    color: colors.textOnPrimary,
    fontSize: responsiveSize(18),
  },
  profileHeaderTextWrap: {
    flex: 1,
    minWidth: 0,
  },
  profileNameText: {
    fontFamily: fonts.bold,
    fontSize: responsiveSize(22),
    color: premium.profileText,
    lineHeight: responsiveSize(26),
  },
  profileEmailText: {
    marginTop: hp(0.1),
    color: premium.profileTextMuted,
    fontFamily: fonts.medium,
    fontSize: responsiveSize(13),
  },
  profileIdSubtext: {
    marginTop: hp(0.2),
    color: premium.profileTextMuted,
    fontFamily: fonts.medium,
    fontSize: responsiveSize(11),
  },
  profileBadgesRow: {
    marginTop: hp(1.8),
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: wp(2.4),
  },
  activeBadge: {
    borderRadius: wp(4.2),
    borderWidth: 1,
    borderColor: premium.profileActiveBorder,
    backgroundColor: premium.profileActiveBg,
    paddingHorizontal: wp(3.4),
    paddingVertical: hp(0.52),
  },
  activeBadgeText: {
    color: premium.profileActiveText,
    fontFamily: fonts.semibold,
    fontSize: responsiveSize(12),
  },
  administratorBadge: {
    borderRadius: wp(4.2),
    borderWidth: 1,
    borderColor: premium.profileRoleBorder,
    backgroundColor: premium.profileRoleBg,
    paddingHorizontal: wp(3.6),
    paddingVertical: hp(0.52),
  },
  administratorBadgeText: {
    color: premium.profileRoleText,
    fontFamily: fonts.semibold,
    fontSize: responsiveSize(12),
    textTransform: 'capitalize',
  },
  profileTabsScrollView: {
    marginTop: hp(1.8),
    flexGrow: 0,
    maxHeight: hp(6.5),
  },
  profileTabsContent: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    paddingBottom: 0,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: premium.profileBorder,
    gap: wp(1.5),
    paddingRight: wp(2),
  },
  profileTabItem: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: hp(0.75),
    paddingBottom: hp(1),
    paddingHorizontal: wp(2.2),
    borderBottomWidth: 3,
    borderBottomColor: 'transparent',
    marginBottom: -StyleSheet.hairlineWidth,
  },
  profileTabActive: {
    borderBottomColor: premium.profileTabActive,
  },
  profileTabText: {
    color: premium.profileTabInactive,
    fontFamily: fonts.medium,
    fontSize: responsiveSize(13),
    textAlign: 'center',
  },
  profileTabTextActive: {
    color: premium.profileTabActive,
    fontFamily: fonts.semibold,
  },
  profileContent: {
    flex: 1,
  },
  profileContentContainer: {
    paddingTop: hp(2),
    gap: hp(3),
    paddingBottom: hp(4),
  },
  profileTabContentWrap: {
    position: 'relative',
    minHeight: hp(12),
  },
  profileTabContent: {
    gap: hp(2),
  },
  skeletonBlock: {
    borderRadius: wp(1.5),
    backgroundColor: premium.profileBorder,
  },
  skeletonRow: {
    gap: hp(0.55),
    marginTop: hp(0.75),
  },
  profileLoadingOverlay: {
    ...StyleSheet.absoluteFill,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.35)',
    borderRadius: wp(4),
  },
  profileSectionCard: {
    borderRadius: wp(4),
    borderWidth: 1,
    borderColor: premium.profileBorder,
    backgroundColor: premium.profileCard,
    paddingHorizontal: wp(3.4),
    paddingVertical: hp(1.55),
    gap: hp(1.15),
    ...Platform.select({
      ios: {
        shadowColor: colors.shadow,
        shadowOffset: {width: 0, height: 2},
        shadowOpacity: colors.background === lightColors.background ? 0.08 : 0.22,
        shadowRadius: 6,
      },
      android: {
        elevation: colors.background === lightColors.background ? 2 : 3,
      },
    }),
  },
  profileSectionTitle: {
    color: premium.profileTextMuted,
    fontFamily: fonts.semibold,
    textTransform: 'uppercase',
    letterSpacing: responsiveSize(1.3),
    fontSize: responsiveSize(12),
  },
  profileSectionSubtitle: {
    flex: 1,
    minWidth: 0,
    color: premium.profileText,
    fontFamily: fonts.semibold,
    fontSize: responsiveSize(17),
  },
  profileRowBlock: {
    gap: hp(0.45),
  },
  profileLabel: {
    color: premium.profileTextMuted,
    fontFamily: fonts.medium,
    textTransform: 'uppercase',
    letterSpacing: responsiveSize(0.8),
    fontSize: responsiveSize(11),
  },
  profileValue: {
    color: premium.profileText,
    fontFamily: fonts.semibold,
    fontSize: responsiveSize(16),
  },
  profileDivider: {
    height: 1,
    backgroundColor: premium.profileBorder,
  },
  profileLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: wp(2),
    flexWrap: 'wrap',
  },
  profileLinkText: {
    color: premium.profileTabActive,
    fontFamily: fonts.semibold,
    fontSize: responsiveSize(12),
  },
  userIdPill: {
    borderRadius: wp(2),
    backgroundColor: premium.profileCardSoft,
    paddingHorizontal: wp(2.2),
    paddingVertical: hp(1),
  },
  profileIdText: {
    color: premium.profileTextMuted,
    fontFamily: fonts.medium,
    fontSize: responsiveSize(11),
  },
  profileSubtleText: {
    color: premium.profileTextMuted,
    fontFamily: fonts.regular,
    fontSize: responsiveSize(12),
    lineHeight: responsiveSize(22),
  },
  profilePrimaryButton: {
    borderRadius: wp(3),
    backgroundColor: premium.profilePrimaryButton,
    paddingVertical: hp(1.2),
    paddingHorizontal: wp(3),
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: hp(5.2),
  },
  profilePrimaryButtonFull: {
    marginTop: hp(0.8),
    alignSelf: 'stretch',
  },
  profileActionFlex: {
    flex: 1,
    minWidth: wp(36),
  },
  profilePrimaryButtonText: {
    color: premium.profilePrimaryButtonText,
    fontFamily: fonts.bold,
    fontSize: responsiveSize(13),
    textTransform: 'uppercase',
    letterSpacing: responsiveSize(0.6),
    textAlign: 'center',
  },
  profileInlineActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'stretch',
    gap: wp(2),
    marginTop: hp(0.4),
  },
  profileRoleOptions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: wp(2),
  },
  profileRoleOption: {
    borderRadius: wp(2.2),
    borderWidth: 1,
    borderColor: premium.profileBorderStrong,
    backgroundColor: premium.profileCardSoft,
    paddingHorizontal: wp(3),
    paddingVertical: hp(0.65),
  },
  profileRoleOptionActive: {
    borderColor: premium.profileTabActive,
    backgroundColor: premium.profileRoleBg,
  },
  profileRoleOptionText: {
    color: premium.profileTextMuted,
    fontFamily: fonts.semibold,
    fontSize: responsiveSize(13),
  },
  profileRoleOptionTextActive: {
    color: premium.profileTabActive,
  },
  profileCountySearch: {
    borderWidth: 1,
    borderColor: premium.profileBorderStrong,
    borderRadius: wp(2),
    backgroundColor: premium.profileCard,
    color: premium.profileText,
    fontFamily: fonts.medium,
    fontSize: responsiveSize(14),
    paddingHorizontal: wp(2.4),
    paddingVertical: hp(0.85),
  },
  profileCountyGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: wp(2),
  },
  profileCountyItem: {
    flexGrow: 1,
    flexBasis: '46%',
    maxWidth: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    gap: wp(1.8),
    borderWidth: 1,
    borderColor: premium.profileBorder,
    borderRadius: wp(2),
    backgroundColor: premium.profileCardSoft,
    paddingHorizontal: wp(2),
    paddingVertical: hp(0.75),
  },
  profileCountyItemSelected: {
    borderColor: premium.profileTabActive,
    backgroundColor: premium.profileRoleBg,
  },
  profileCountyCheck: {
    width: wp(4.2),
    height: wp(4.2),
    borderRadius: wp(1),
    borderWidth: 1,
    borderColor: premium.profileBorderStrong,
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileCountyCheckSelected: {
    backgroundColor: premium.profileTabActive,
    borderColor: premium.profileTabActive,
  },
  profileCountyName: {
    flex: 1,
    minWidth: 0,
    color: premium.profileText,
    fontFamily: fonts.medium,
    fontSize: responsiveSize(12),
  },
  profileSectionHeaderRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: wp(2),
  },
  profileSectionHeaderTextWrap: {
    flex: 1,
    minWidth: 0,
    gap: hp(0.5),
  },
  profileHeading: {
    flex: 1,
    minWidth: 0,
    color: premium.profileText,
    fontFamily: fonts.bold,
    fontSize: responsiveSize(16),
    lineHeight: responsiveSize(22),
  },
  profileOutlineButton: {
    borderRadius: wp(2.3),
    borderWidth: 1,
    borderColor: premium.profileBorderStrong,
    backgroundColor: premium.profileCardSoft,
    paddingHorizontal: wp(3),
    paddingVertical: hp(1),
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: hp(5.2),
  },
  profileOutlineButtonCompact: {
    flexShrink: 0,
    paddingHorizontal: wp(2.6),
    paddingVertical: hp(0.75),
    minHeight: hp(4.2),
  },
  profileOutlineButtonText: {
    color: premium.profileText,
    fontFamily: fonts.semibold,
    fontSize: responsiveSize(13),
    textAlign: 'center',
  },
  profilePlaceholderCard: {
    marginTop: hp(0.6),
    borderRadius: wp(3),
    borderWidth: 1,
    borderColor: premium.profileBorder,
    borderStyle: 'dashed',
    minHeight: hp(18),
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: wp(4),
  },
  profilePlaceholderText: {
    color: premium.profileTextMuted,
    textAlign: 'center',
    fontFamily: fonts.medium,
    fontSize: responsiveSize(16),
    lineHeight: responsiveSize(24),
  },
  profileTalkgroupList: {
    gap: hp(1),
  },
  profileTalkgroupItem: {
    borderWidth: 1,
    borderColor: premium.profileBorder,
    borderRadius: wp(2.4),
    backgroundColor: premium.profileCardSoft,
    paddingHorizontal: wp(2.6),
    paddingVertical: hp(1),
    gap: hp(0.8),
  },
  profileTalkgroupHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: wp(2),
  },
  profileTalkgroupCounty: {
    flex: 1,
    minWidth: 0,
    color: premium.profileTextMuted,
    fontFamily: fonts.semibold,
    fontSize: responsiveSize(12),
  },
  profileTalkgroupInput: {
    borderWidth: 1,
    borderColor: premium.profileBorderStrong,
    borderRadius: wp(2),
    backgroundColor: premium.profileCard,
    color: premium.profileText,
    fontFamily: fonts.medium,
    fontSize: responsiveSize(14),
    paddingHorizontal: wp(2.4),
    paddingVertical: hp(0.95),
  },
  profileGhostCard: {
    borderRadius: wp(2.8),
    borderWidth: 1,
    borderColor: premium.profileBorder,
    minHeight: hp(7.2),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: premium.profileCardSoft,
  },
  profileGhostCardText: {
    color: premium.profileGhostText,
    fontFamily: fonts.semibold,
    fontSize: responsiveSize(18),
  },
  profileSectionHeaderInline: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: wp(2),
  },
  profileSectionHeading: {
    flex: 1,
    minWidth: wp(40),
    color: premium.profileText,
    fontFamily: fonts.bold,
    fontSize: responsiveSize(16),
    lineHeight: responsiveSize(22),
  },
  activeCountPill: {
    flexShrink: 1,
    maxWidth: '100%',
    borderRadius: wp(3),
    backgroundColor: premium.profileRoleBg,
    borderWidth: 1,
    borderColor: premium.profileRoleBorder,
    paddingHorizontal: wp(2.5),
    paddingVertical: hp(0.7),
  },
  activeCountText: {
    color: premium.profileRoleText,
    fontFamily: fonts.bold,
    fontSize: responsiveSize(11),
  },
  sessionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: wp(2),
  },
  sessionTitleWrap: {
    flex: 1,
    minWidth: 0,
    gap: hp(0.35),
  },
  sessionTitle: {
    color: premium.profileText,
    fontFamily: fonts.bold,
    fontSize: responsiveSize(16),
    lineHeight: responsiveSize(27),
  },
  currentSessionDot: {
    color: premium.profileTabActive,
    fontFamily: fonts.semibold,
    fontSize: responsiveSize(12),
  },
  revokeButton: {
    flexShrink: 0,
    borderRadius: wp(2.3),
    borderWidth: 1,
    borderColor: premium.profileDangerBorder,
    backgroundColor: premium.profileDangerBg,
    paddingHorizontal: wp(2.5),
    paddingVertical: hp(0.85),
    minHeight: hp(4.2),
    justifyContent: 'center',
  },
  revokeButtonText: {
    color: premium.profileDangerText,
    fontFamily: fonts.semibold,
    fontSize: responsiveSize(12),
  },
  sessionGrid: {
    marginTop: hp(0.7),
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: wp(3),
  },
  sessionGridCell: {
    flex: 1,
    minWidth: wp(38),
  },
  sessionSignedRow: {
    marginTop: hp(0.65),
    gap: hp(0.4),
  },
  profileOutlineDangerButton: {
    marginTop: hp(0.95),
    alignSelf: 'stretch',
    borderRadius: wp(2.6),
    borderWidth: 1,
    borderColor: premium.profileWarningBorder,
    backgroundColor: premium.profileWarningBg,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: hp(1.15),
    paddingHorizontal: wp(3),
    minHeight: hp(5.2),
  },
  profileOutlineDangerButtonText: {
    color: premium.profileWarningText,
    fontFamily: fonts.bold,
    fontSize: responsiveSize(13),
    textAlign: 'center',
  },
  infoAlertCard: {
    marginTop: hp(0.55),
    borderRadius: wp(2.6),
    borderWidth: 1,
    borderColor: premium.profileInfoBorder,
    backgroundColor: premium.profileInfoBg,
    paddingHorizontal: wp(3),
    paddingVertical: hp(1.2),
  },
  infoAlertText: {
    color: premium.profileInfoText,
    fontFamily: fonts.medium,
    fontSize: responsiveSize(12),
    lineHeight: responsiveSize(20),
  },
  profileTimelineWrap: {
    gap: hp(1.1),
  },
  timelineItem: {
    flexDirection: 'row',
    alignItems: 'stretch',
    gap: wp(2.2),
  },
  timelineColumn: {
    width: wp(6),
    alignItems: 'center',
  },
  timelineDot: {
    marginTop: hp(1.2),
    width: wp(2.3),
    height: wp(2.3),
    borderRadius: wp(1.15),
    backgroundColor: premium.profileTextMuted,
  },
  timelineLine: {
    flex: 1,
    width: 1,
    backgroundColor: premium.profileBorderStrong,
    marginTop: hp(0.65),
  },
  timelineCard: {
    flex: 1,
    borderRadius: wp(3),
    borderWidth: 1,
    borderColor: premium.profileBorder,
    backgroundColor: premium.profileCard,
    paddingHorizontal: wp(3),
    paddingVertical: hp(1.3),
    ...Platform.select({
      ios: {
        shadowColor: colors.shadow,
        shadowOffset: {width: 0, height: 2},
        shadowOpacity: colors.background === lightColors.background ? 0.08 : 0.22,
        shadowRadius: 6,
      },
      android: {
        elevation: colors.background === lightColors.background ? 2 : 3,
      },
    }),
  },
  permissionsStack: {
    gap: hp(2),
  },
  profileReloadRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: wp(1.2),
  },
  severityModeCard: {
    borderRadius: wp(2.8),
    borderWidth: 1,
    borderColor: premium.profileBorder,
    backgroundColor: premium.profileCardSoft,
    paddingHorizontal: wp(3),
    paddingVertical: hp(1.1),
    gap: hp(0.45),
  },
  severityModeCardActive: {
    borderColor: premium.profileTabActive,
    backgroundColor: premium.profileRoleBg,
  },
  severityModeTitle: {
    color: premium.profileText,
    fontFamily: fonts.semibold,
    fontSize: responsiveSize(14),
  },
  severityModeHint: {
    color: premium.profileTextMuted,
    fontFamily: fonts.regular,
    fontSize: responsiveSize(11),
    lineHeight: responsiveSize(16),
  },
  severityPickerCard: {
    marginTop: hp(0.5),
    borderRadius: wp(2.8),
    borderWidth: 1,
    borderColor: premium.profileBorder,
    backgroundColor: premium.profileCard,
    paddingHorizontal: wp(3),
    paddingVertical: hp(1.2),
    gap: hp(1),
  },
  severityPickerTitle: {
    color: premium.profileTextMuted,
    fontFamily: fonts.bold,
    fontSize: responsiveSize(10),
    letterSpacing: responsiveSize(0.8),
  },
  severityOptionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: wp(2.5),
    paddingVertical: hp(0.35),
  },
  severityBadgeHigh: {
    backgroundColor: 'rgba(239, 68, 68, 0.12)',
    borderColor: 'rgba(239, 68, 68, 0.35)',
  },
  severityBadgeMedium: {
    backgroundColor: 'rgba(245, 158, 11, 0.12)',
    borderColor: 'rgba(245, 158, 11, 0.28)',
  },
  severityBadgeLow: {
    backgroundColor: 'rgba(34, 197, 94, 0.12)',
    borderColor: 'rgba(34, 197, 94, 0.28)',
  },
  severityLevelBadge: {
    borderRadius: wp(3),
    borderWidth: 1,
    paddingHorizontal: wp(2.5),
    paddingVertical: hp(0.25),
    minWidth: wp(16),
    alignItems: 'center',
  },
  severityLevelBadgeText: {
    fontFamily: fonts.bold,
    fontSize: responsiveSize(11),
  },
  severityLevelTextHigh: {
    color: '#EF4444',
  },
  severityLevelTextMedium: {
    color: colors.warning,
  },
  severityLevelTextLow: {
    color: colors.live,
  },
  profileTalkgroupEntryLabel: {
    color: premium.profileTextMuted,
    fontFamily: fonts.bold,
    fontSize: responsiveSize(10),
    letterSpacing: responsiveSize(0.8),
  },
  profileFieldLabel: {
    color: premium.profileTextMuted,
    fontFamily: fonts.medium,
    fontSize: responsiveSize(11),
    marginTop: hp(0.35),
  },
  profileCountySelect: {
    marginTop: hp(0.25),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: premium.profileBorderStrong,
    borderRadius: wp(2),
    backgroundColor: premium.profileCard,
    paddingHorizontal: wp(2.4),
    paddingVertical: hp(0.9),
    gap: wp(2),
  },
  profileCountySelectText: {
    flex: 1,
    minWidth: 0,
    color: premium.profileText,
    fontFamily: fonts.medium,
    fontSize: responsiveSize(14),
  },
  profileCountyOptions: {
    marginTop: hp(0.35),
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: wp(1.5),
  },
  profileCountyOptionChip: {
    borderRadius: wp(4),
    borderWidth: 1,
    borderColor: premium.profileBorder,
    backgroundColor: premium.profileCardSoft,
    paddingHorizontal: wp(2.4),
    paddingVertical: hp(0.45),
  },
  profileCountyOptionChipActive: {
    borderColor: premium.profileTabActive,
    backgroundColor: premium.profileRoleBg,
  },
  profileCountyOptionChipText: {
    color: premium.profileText,
    fontFamily: fonts.medium,
    fontSize: responsiveSize(12),
  },
  profileCountyOptionChipTextActive: {
    color: premium.profileTabActive,
    fontFamily: fonts.semibold,
  },
  closeProfileButton: {
    borderRadius: wp(3),
    borderWidth: 1,
    borderColor: premium.profileBorderStrong,
    backgroundColor: premium.profileCard,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: hp(1.3),
  },
  closeProfileButtonText: {
    color: premium.profileText,
    fontFamily: fonts.semibold,
    fontSize: responsiveSize(14),
  },
  profileLoadingWrap: {
    paddingVertical: hp(8),
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileErrorText: {
    marginTop: hp(1),
    color: premium.profileErrorText,
    fontFamily: fonts.medium,
    fontSize: responsiveSize(12),
    textAlign: 'center',
  },
  });
};
