import {StyleSheet} from 'react-native';
import {hp, wp, responsiveSize} from '../../utils/responsive';

export const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  bottomSheet: {
    backgroundColor: '#1a1f2e',
    borderTopLeftRadius: wp(6),
    borderTopRightRadius: wp(6),
    paddingTop: hp(2),
    maxHeight: '90%',
    paddingBottom: hp(3),
  },
  sheetHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: wp(4),
    paddingBottom: hp(2),
  },
  titleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: wp(2),
  },
  filterIcon: {
    fontSize: responsiveSize(24),
    color: '#94a3b8',
  },
  sheetTitle: {
    fontSize: responsiveSize(22),
    fontWeight: '700',
    color: '#f8fafc',
  },
  resetButton: {
    fontSize: responsiveSize(14),
    color: '#64748b',
    fontWeight: '600',
    marginRight: wp(4),
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  closeButton: {
    width: wp(8),
    height: wp(8),
    borderRadius: wp(4),
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  closeIcon: {
    fontSize: responsiveSize(14),
    color: '#94a3b8',
    fontWeight: '700',
  },
  recordsInfoContainer: {
    paddingHorizontal: wp(4),
    paddingBottom: hp(1.5),
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.08)',
  },
  recordsMatchedText: {
    fontSize: responsiveSize(12),
    color: '#94a3b8',
    letterSpacing: 0.5,
    fontWeight: '700',
  },
  scrollContainer: {
    paddingHorizontal: wp(4),
    maxHeight: '70%',
  },
  section: {
    marginTop: hp(2.5),
    marginBottom: hp(2.5),
  },
  sectionTitle: {
    fontSize: responsiveSize(11),
    fontWeight: '700',
    color: '#94a3b8',
    letterSpacing: 1.2,
    marginBottom: hp(1.5),
    textTransform: 'uppercase',
  },
  presetsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: hp(2),
    gap: wp(2),
  },
  presetButton: {
    paddingVertical: hp(0.9),
    paddingHorizontal: wp(3),
    borderRadius: wp(5),
    borderWidth: 1.5,
    borderColor: 'rgba(255, 255, 255, 0.15)',
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
  },
  presetButtonText: {
    fontSize: responsiveSize(13),
    color: '#cbd5e1',
    fontWeight: '500',
  },
  dateRow: {
    flexDirection: 'row',
    gap: wp(2.5),
  },
  dateColumn: {
    flex: 1,
  },
  label: {
    fontSize: responsiveSize(12),
    color: '#94a3b8',
    fontWeight: '600',
    marginBottom: hp(0.8),
  },
  dateInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(15, 23, 42, 0.8)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: wp(2),
    paddingHorizontal: wp(3),
  },
  dateInput: {
    flex: 1,
    paddingVertical: hp(1.2),
    fontSize: responsiveSize(14),
    color: '#cbd5e1',
  },
  calendarIcon: {
    fontSize: responsiveSize(16),
    marginLeft: wp(2),
  },
  searchGroup: {
    marginBottom: hp(2),
  },
  searchInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(15, 23, 42, 0.8)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: wp(2),
    paddingHorizontal: wp(3),
  },
  searchInput: {
    flex: 1,
    paddingVertical: hp(1.2),
    fontSize: responsiveSize(14),
    color: '#cbd5e1',
  },
  searchIcon: {
    fontSize: responsiveSize(16),
    marginLeft: wp(2),
  },
  talkgroupRow: {
    flexDirection: 'row',
    gap: wp(2.5),
  },
  talkgroupColumn: {
    flex: 1,
  },
  talkgroupInput: {
    backgroundColor: 'rgba(15, 23, 42, 0.8)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: wp(2),
    paddingHorizontal: wp(3),
    paddingVertical: hp(1.2),
    fontSize: responsiveSize(14),
    color: '#cbd5e1',
  },
  statusGroup: {
    marginBottom: hp(1.5),
  },
  statusDropdown: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: 'rgba(15, 23, 42, 0.8)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: wp(2),
    paddingHorizontal: wp(3),
    paddingVertical: hp(1.2),
  },
  statusDropdownText: {
    fontSize: responsiveSize(14),
    color: '#cbd5e1',
  },
  dropdownIcon: {
    fontSize: responsiveSize(12),
    color: '#64748b',
  },
  infoBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(49, 212, 146, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(49, 212, 146, 0.3)',
    borderRadius: wp(2),
    paddingHorizontal: wp(3),
    paddingVertical: hp(1.2),
    marginTop: hp(1.5),
  },
  infoDot: {
    width: wp(2),
    height: wp(2),
    borderRadius: wp(1),
    backgroundColor: '#31D492',
    marginRight: wp(2),
  },
  infoText: {
    fontSize: responsiveSize(12),
    color: '#31D492',
    fontWeight: '500',
    flex: 1,
  },
  applyButton: {
    marginHorizontal: wp(4),
    marginTop: hp(2),
    paddingVertical: hp(1.5),
    backgroundColor: '#6366f1',
    borderRadius: wp(3),
    alignItems: 'center',
  },
  applyButtonText: {
    fontSize: responsiveSize(16),
    color: '#ffffff',
    fontWeight: '700',
  },
  dropdownOptionsContainer: {
    marginTop: hp(0.5),
    backgroundColor: 'rgba(15, 23, 42, 0.95)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: wp(2),
    overflow: 'hidden',
    zIndex: 1000,
  },
  dropdownOption: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: wp(4),
    paddingVertical: hp(1.5),
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.05)',
  },
  dropdownOptionText: {
    fontSize: responsiveSize(14),
    color: '#94a3b8',
  },
  dropdownOptionTextActive: {
    color: '#6366f1',
    fontWeight: '600',
  },
  checkIcon: {
    fontSize: responsiveSize(14),
    color: '#6366f1',
  },
});
