import {StyleSheet} from 'react-native';
import {fonts} from '../../constants';
import type {AppColors} from '../../theme/types';
import {hp, wp, responsiveSize} from '../../utils/responsive';

export const createStyles = (colors: AppColors) =>
  StyleSheet.create({
    overlay: {
      flex: 1,
      backgroundColor: colors.overlay,
    },
    bottomSheet: {
      backgroundColor: colors.surfaceElevated,
      borderTopLeftRadius: wp(6),
      borderTopRightRadius: wp(6),
      paddingTop: hp(2),
      maxHeight: '90%',
      paddingBottom: hp(3),
    },
    sheetHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: wp(4),
      paddingBottom: hp(2),
    },
    titleContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: wp(2),
    },
    filterIcon: {
      fontSize: responsiveSize(24),
      fontFamily: fonts.regular,
      color: colors.textSecondary,
    },
    sheetTitle: {
      fontSize: responsiveSize(22),
      fontFamily: fonts.semibold,
      color: colors.text,
    },
    resetButton: {
      fontSize: responsiveSize(14),
      color: colors.textMuted,
      fontFamily: fonts.semibold,
      marginRight: wp(4),
    },
    headerRight: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    closeButton: {
      width: wp(8),
      height: wp(8),
      borderRadius: wp(4),
      backgroundColor: colors.menuItemBorder,
      alignItems: 'center',
      justifyContent: 'center',
    },
    closeIcon: {
      fontSize: responsiveSize(14),
      color: colors.textSecondary,
      fontFamily: fonts.semibold,
    },
    recordsInfoContainer: {
      paddingHorizontal: wp(4),
      paddingBottom: hp(1.5),
      borderBottomWidth: 1,
      borderBottomColor: colors.menuItemBorder,
    },
    recordsMatchedText: {
      fontSize: responsiveSize(12),
      color: colors.textSecondary,
      letterSpacing: responsiveSize(0.5),
      fontFamily: fonts.semibold,
    },
    scrollContainer: {
      paddingHorizontal: wp(4),
      maxHeight: '70%',
    },
    searchRowSection: {
      flexDirection: 'row',
      alignItems: 'flex-end',
      gap: wp(2.5),
      marginTop: hp(2),
      marginBottom: hp(1.5),
    },
    searchRowField: {
      flex: 1,
      minWidth: 0,
    },
    section: {
      marginTop: hp(1.5),
      marginBottom: hp(2),
    },
    sectionTitle: {
      fontSize: responsiveSize(11),
      fontFamily: fonts.semibold,
      color: colors.textSecondary,
      letterSpacing: responsiveSize(1.2),
      marginBottom: hp(1.5),
      textTransform: 'uppercase',
    },
    presetsContainer: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      marginBottom: hp(2),
      gap: wp(2),
    },
    presetButton: {
      paddingVertical: hp(0.9),
      paddingHorizontal: wp(3),
      borderRadius: wp(5),
      borderWidth: 1.5,
      borderColor: colors.borderMuted,
      backgroundColor: colors.inputBackground,
    },
    presetButtonText: {
      fontSize: responsiveSize(13),
      color: colors.text,
      fontFamily: fonts.medium,
    },
    dateRow: {
      flexDirection: 'row',
      gap: wp(2.5),
    },
    dateColumn: {
      flex: 1,
    },
    label: {
      fontSize: responsiveSize(12),
      color: colors.textSecondary,
      fontFamily: fonts.semibold,
      marginBottom: hp(0.8),
    },
    dateInputContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.inputBackground,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      borderRadius: wp(2),
      paddingHorizontal: wp(3),
    },
    dateInput: {
      flex: 1,
      paddingVertical: hp(1.2),
      fontSize: responsiveSize(14),
      fontFamily: fonts.regular,
      color: colors.text,
    },
    calendarIcon: {
      fontSize: responsiveSize(16),
      fontFamily: fonts.regular,
      marginLeft: wp(2),
    },
    searchGroup: {
      marginBottom: hp(2),
    },
    searchInputContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.inputBackground,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      borderRadius: wp(2),
      paddingHorizontal: wp(3),
      minHeight: hp(5.2),
    },
    searchInput: {
      flex: 1,
      paddingVertical: hp(1.1),
      fontSize: responsiveSize(13),
      fontFamily: fonts.regular,
      color: colors.text,
    },
    searchIcon: {
      fontSize: responsiveSize(16),
      fontFamily: fonts.regular,
      marginLeft: wp(2),
    },
    talkgroupRow: {
      flexDirection: 'row',
      gap: wp(2.5),
    },
    talkgroupColumn: {
      flex: 1,
    },
    talkgroupInput: {
      backgroundColor: colors.inputBackground,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      borderRadius: wp(2),
      paddingHorizontal: wp(3),
      paddingVertical: hp(1.1),
      fontSize: responsiveSize(13),
      fontFamily: fonts.regular,
      color: colors.text,
      minHeight: hp(5.2),
    },
    statusGroup: {
      marginBottom: hp(1.5),
    },
    statusDropdown: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      backgroundColor: colors.inputBackground,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      borderRadius: wp(2),
      paddingHorizontal: wp(3),
      paddingVertical: hp(1.2),
    },
    statusDropdownText: {
      fontSize: responsiveSize(14),
      fontFamily: fonts.regular,
      color: colors.text,
    },
    dropdownIcon: {
      fontSize: responsiveSize(12),
      fontFamily: fonts.regular,
      color: colors.textMuted,
    },
    infoBox: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: `${colors.live}1A`,
      borderWidth: 1,
      borderColor: 'rgba(49, 212, 146, 0.3)',
      borderRadius: wp(2),
      paddingHorizontal: wp(3),
      paddingVertical: hp(1.2),
      marginTop: hp(1.5),
    },
    infoDot: {
      width: wp(2),
      height: wp(2),
      borderRadius: wp(1),
      backgroundColor: colors.success,
      marginRight: wp(2),
    },
    infoText: {
      fontSize: responsiveSize(12),
      color: colors.success,
      fontFamily: fonts.medium,
      flex: 1,
    },
    applyButton: {
      marginHorizontal: wp(4),
      marginTop: hp(2),
      paddingVertical: hp(1.5),
      backgroundColor: colors.primary,
      borderRadius: wp(3),
      alignItems: 'center',
    },
    applyButtonText: {
      fontSize: responsiveSize(16),
      color: colors.textOnPrimary,
      fontFamily: fonts.semibold,
    },
    dropdownOptionsContainer: {
      marginTop: hp(0.5),
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      borderRadius: wp(2),
      overflow: 'hidden',
      zIndex: 1000,
    },
    dropdownOption: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: wp(4),
      paddingVertical: hp(1.5),
      borderBottomWidth: 1,
      borderBottomColor: colors.menuItemBorder,
    },
    dropdownOptionText: {
      fontSize: responsiveSize(14),
      fontFamily: fonts.regular,
      color: colors.textSecondary,
    },
    dropdownOptionTextActive: {
      color: colors.primary,
      fontFamily: fonts.semibold,
    },
    checkIcon: {
      fontSize: responsiveSize(14),
      fontFamily: fonts.semibold,
      color: colors.primary,
    },
    presetButtonActive: {
      borderColor: colors.primary,
      backgroundColor: colors.primaryTint,
    },
    presetButtonTextActive: {
      color: colors.primary,
      fontFamily: fonts.semibold,
    },
    priorityContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: hp(2.5),
      gap: wp(1.5),
    },
    priorityOption: {
      flex: 1,
      paddingVertical: hp(0.8),
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: wp(5),
      borderWidth: 1.5,
      borderColor: colors.borderMuted,
      backgroundColor: colors.inputBackground,
    },
    priorityOptionActive: {
      borderColor: colors.primary,
      backgroundColor: colors.primaryTint,
    },
    priorityOptionText: {
      fontSize: responsiveSize(13),
      color: colors.text,
      fontFamily: fonts.medium,
    },
    priorityOptionTextActive: {
      color: colors.primary,
      fontFamily: fonts.semibold,
    },
    searchIconLeft: {
      marginRight: wp(2),
    },
  });
